openapi: 3.0.3
info:
  title: Small KMS API
  version: 0.1.0
servers:
- description: Local server
  url: http://localhost:9000
paths:
  /v1/admin/ca/{id}:
    get:
      description: Get CA Metadata
      operationId: AdminGetCAMetadata
      parameters:
      - description: Identifier of the CA certificate (e.g. root)
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CertificateMetadata'
          description: A JSON array of user names
      summary: Get CA Metadata
      tags:
      - admin
components:
  schemas:
    CertificateMetadata:
      example:
        id: id
      properties:
        id:
          type: string
      required:
      - id
      title: CertificateMetadata
      type: object
