services:

  krakend:
    image: devopsfaith/krakend
    ports:
      - "8080:8080"
    volumes:
      - ./krakend/dev-config:/etc/krakend

  radius:
    build: radius/docker
    volumes:
      - ./radius/log:/opt/var/log/radius
    links:
      - krakend:krakend
    #tty: true
    #stdin_open: true
    #command: /bin/sh

