openapi: 3.0.3
info:
  title: Small KMS API
  version: 0.1.0
servers:
  - url: http://localhost:9000
    description: Local server
paths:
  /v1/admin/ca/{id}:
    get:
      tags:
        - admin
      summary: Get CA Metadata
      description: Get CA Metadata
      operationId: AdminGetCAMetadata
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Identifier of the CA certificate (e.g. root)
      responses:
        "200": # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                title: CertificateMetadata
                type: object
                properties:
                  id:
                    type: string
                required:
                  - id
