/*
 * Small KMS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"

	// WARNING!
	// Pass --git-repo-id and --git-user-id properties when generating the code
	//
	sw "github.com/stephenzsy/small-kms/backend/go"
	"github.com/stephenzsy/small-kms/backend/go/config"
)

func main() {
	log.Printf("Server started")

	config.Initialize()

	router := sw.NewRouter()

	log.Fatal(router.Run("localhost:9000"))
}
