openapi: 3.0.3
info:
  title: Small KMS Admin API Shared Models
  version: 0.1.0
paths: {}
components:
  schemas:
    NamespaceType:
      type: string
      enum:
        - any
        - root-ca
        - intermediate-ca
        - service-principal
        - group
        - device
        - user
        - application
      x-enum-varnames:
        - NSType_Any
        - NSType_RootCA
        - NSType_IntCA
        - NSType_ServicePrincipal
        - NSType_Group
        - NSType_Device
        - NSType_User
        - NSType_Application
    JwkAlg:
      type: string
      enum:
        - RS256
        - RS384
        - RS512
        - ES256
        - ES384
      x-enum-varnames:
        - AlgRS256
        - AlgRS384
        - AlgRS512
        - AlgES256
        - AlgES384
    JwtKty:
      type: string
      enum:
        - RSA
        - EC
      x-enum-varnames:
        - KeyTypeRSA
        - KeyTypeEC
    JwtCrv:
      type: string
      enum:
        - P-256
        - P-384
      x-enum-varnames:
        - CurveNameP256
        - CurveNameP384
    JwkKeyOperation:
      type: string
      enum:
        - sign
        - verify
        - encrypt
        - decrypt
        - wrapKey
        - unwrapKey
      x-enum-varnames:
        - KeyOpSign
        - KeyOpVerify
        - KeyOpEncrypt
        - KeyOpDecrypt
        - KeyOpWrapKey
        - KeyOpUnwrapKey
      x-go-name: KeyOp
    JwkProperties:
      type: object
      description: Property bag of JSON Web Key (RFC 7517) with additional fields, all bytes are base64url encoded
      properties:
        alg:
          $ref: "#/components/schemas/JwkAlg"
        kty:
          $ref: "#/components/schemas/JwtKty"
        key_size:
          description: RSA key size
          type: integer
        key_ops:
          $ref: "#/components/schemas/JwkKeyOperation"
        n:
          description: RSA modulus
          type: string
        e:
          description: RSA exponent
          type: string
        crv:
          $ref: "#/components/schemas/JwtCrv"
        x:
          description: EC x coordinate
          type: string
        y:
          description: EC y coordinate
          type: string
        kid:
          description: Key ID
          type: string
          x-go-name: KeyID
        x5u:
          x-go-name: CertificateURL
          description: X.509 certificate URL
          type: string
        x5c:
          description: X.509 certificate chain
          type: array
          items:
            type: string
          x-go-name: CertificateChain
          x-go-type-skip-optional-pointer: true
        x5t:
          description: X.509 certificate SHA-1 thumbprint
          type: string
          x-go-name: CertificateThumbprint
        x5t#S256:
          description: X.509 certificate SHA-256 thumbprint
          type: string
          x-go-name: CertificateThumbprintSHA256
      required:
        - kty
