openapi: 3.0.3
info:
  title: Small KMS Shared Models
  version: 0.1.1
paths: {}
components:
  schemas:
    AgentCallbackRequest:
      type: object
      properties:
        configVersion:
          type: string
        serviceRuntime:
          $ref: "#/components/schemas/ServiceRuntimeInfo"
      required:
        - configName
    AgentConfigName:
      type: string
      enum:
        - heartbeat
        - agent-active-host-bootstrap
        - agent-active-server
      x-enum-varnames:
        - AgentConfigNameHeartbeat
        - AgentConfigNameActiveHostBootstrap
        - AgentConfigNameActiveServer
    AgentConfiguration:
      type: object
      properties:
        config:
          $ref: "#/components/schemas/AgentConfigurationParameters"
        version:
          type: string
          description: >
            Version of the agent configuration
        nextRefreshToken:
          type: string
        nextRefreshAfter:
          type: string
          format: date-time
      required:
        - config
        - version
        - lastEvaluated
    AgentConfigurationAgentActiveHostBootstrap:
      type: object
      properties:
        name:
          $ref: "#/components/schemas/AgentConfigName"
        controllerContainer:
          $ref: "#/components/schemas/AgentConfigurationActiveHostControllerContainer"
      required:
        - name
        - controllerContainer
    AgentConfigurationActiveHostControllerContainer:
      type: object
      properties:
        imageRefStr:
          type: string
      required:
        - imageRefStr
    AgentConfigurationAgentActiveServer:
      type: object
      properties:
        name:
          $ref: "#/components/schemas/AgentConfigName"
        endpointUrl:
          description: >
            (Admin server only property to call agent)
          type: string
        serverCertificateTemplateId:
          $ref: "#/components/schemas/Identifier"
        authorizedCertificateTemplateId:
          $ref: "#/components/schemas/Identifier"
        serverCertificateId:
          description: (Read-only)
          $ref: "#/components/schemas/Identifier"
        authorizedCertificateIds:
          type: array
          description: (Read-only)
          x-go-type-skip-optional-pointer: true
          items:
            $ref: "#/components/schemas/Identifier"
        extraAuthorizedCertificateSha384Fingerprints:
          type: array
          x-go-type-skip-optional-pointer: true
          items:
            $ref: "#/components/schemas/CertificateFingerprint"
      required:
        - name
    AgentConfigurationParameters:
      oneOf:
        - $ref: "#/components/schemas/AgentConfigurationAgentActiveHostBootstrap"
        - $ref: "#/components/schemas/AgentConfigurationAgentActiveServer"
      discriminator:
        propertyName: name
        mapping:
          agent-active-host-bootstrap: "#/components/schemas/AgentConfigurationAgentActiveHostBootstrap"
          agent-active-server: "#/components/schemas/AgentConfigurationAgentActiveServer"
    CertificateFingerprint:
      type: string
      x-go-type: certificateFingerprintImpl
    CertificateInfo:
      allOf:
        - $ref: "#/components/schemas/CertificateRef"
        - $ref: "#/components/schemas/CertificateInfoFields"
        - x-go-type: certificateInfoComposed
    CertificateInfoFields:
      type: object
      properties:
        notBefore:
          description: Expiration date of the certificate
          type: string
          format: date-time
        subjectAlternativeNames:
          $ref: "#/components/schemas/SubjectAlternativeNames"
        usages:
          type: array
          items:
            $ref: "#/components/schemas/CertificateUsage"
        issuer:
          description: locator for issuer certificate
          $ref: "#/components/schemas/ResourceLocator"
        jwk:
          $ref: "#/components/schemas/JwkProperties"
        pem:
          type: string
      required:
        - notBefore
        - jwk
        - usages
        - issuer
    CertificateRef:
      allOf:
        - $ref: "#/components/schemas/ResourceRef"
        - $ref: "#/components/schemas/CertificateRefFields"
        - x-go-type: certificateRefComposed
    CertificateRefFields:
      type: object
      properties:
        thumbprint:
          description: X.509 certificate SHA-1 thumbprint
          $ref: "#/components/schemas/CertificateFingerprint"
        subjectCommonName:
          description: Common name
          type: string
        notAfter:
          description: Expiration date of the certificate
          type: string
          format: date-time
        template:
          $ref: "#/components/schemas/ResourceLocator"
        isIssued:
          description: Whether the certificate has been issued
          type: boolean
      required:
        - thumbprint
        - subjectCommonName
        - notAfter
        - template
        - isIssued
    CertificateUsage:
      type: string
      enum:
        - ca
        - caRoot
        - serverAuth
        - clientAuth
      x-enum-varnames:
        - CertUsageCA
        - CertUsageCARoot
        - CertUsageServerAuth
        - CertUsageClientAuth
    DockerInfo:
      type: object
      x-go-type: types.Info
      x-go-type-import:
        path: "github.com/docker/docker/api/types"
    Identifier:
      type: string
      x-go-type: identifierImpl
    JwkAlg:
      type: string
      enum:
        - RS256
        - RS384
        - RS512
        - ES256
        - ES384
      x-enum-varnames:
        - AlgRS256
        - AlgRS384
        - AlgRS512
        - AlgES256
        - AlgES384
    JwkCrv:
      type: string
      enum:
        - P-256
        - P-384
      x-enum-varnames:
        - CurveNameP256
        - CurveNameP384
    JwtKty:
      type: string
      enum:
        - RSA
        - EC
      x-enum-varnames:
        - KeyTypeRSA
        - KeyTypeEC
    JwkKeyOperation:
      type: string
      enum:
        - sign
        - verify
        - encrypt
        - decrypt
        - wrapKey
        - unwrapKey
      x-enum-varnames:
        - KeyOpSign
        - KeyOpVerify
        - KeyOpEncrypt
        - KeyOpDecrypt
        - KeyOpWrapKey
        - KeyOpUnwrapKey
    JwkProperties:
      type: object
      description: Property bag of JSON Web Key (RFC 7517) with additional fields, all bytes are base64url encoded
      properties:
        alg:
          $ref: "#/components/schemas/JwkAlg"
        kty:
          $ref: "#/components/schemas/JwtKty"
        key_size:
          description: RSA key size
          type: integer
          format: int32
        key_ops:
          $ref: "#/components/schemas/JwkKeyOperation"
        n:
          description: RSA modulus
          type: string
          x-go-type: Base64RawURLEncodableBytes
          x-go-type-skip-optional-pointer: true
        e:
          description: RSA exponent
          type: string
          x-go-type: Base64RawURLEncodableBytes
          x-go-type-skip-optional-pointer: true
        crv:
          $ref: "#/components/schemas/JwkCrv"
        x:
          description: EC x coordinate
          type: string
          x-go-type: Base64RawURLEncodableBytes
          x-go-type-skip-optional-pointer: true
        y:
          description: EC y coordinate
          type: string
          x-go-type: Base64RawURLEncodableBytes
          x-go-type-skip-optional-pointer: true
        kid:
          description: Key ID
          type: string
          x-go-name: KeyID
        x5u:
          x-go-name: CertificateURL
          description: X.509 certificate URL
          type: string
        x5c:
          description: X.509 certificate chain
          type: array
          items:
            type: string
            x-go-type: Base64RawURLEncodableBytes
          x-go-name: CertificateChain
          x-go-type-skip-optional-pointer: true
        x5t:
          description: X.509 certificate SHA-1 thumbprint
          type: string
          x-go-type: Base64RawURLEncodableBytes
          x-go-name: CertificateThumbprint
          x-go-type-skip-optional-pointer: true
        x5t#S256:
          description: X.509 certificate SHA-256 thumbprint
          type: string
          x-go-type: Base64RawURLEncodableBytes
          x-go-name: CertificateThumbprintSHA256
          x-go-type-skip-optional-pointer: true
      required:
        - kty
    NamespaceIdentifier:
      type: string
      x-go-type: identifierWithKind[NamespaceKind]
    NamespaceKind:
      type: string
      enum:
        - sys
        - profile
        - ca-root
        - ca-int
        - service-principal
        - group
        - device
        - user
        - application
      x-enum-varnames:
        - NamespaceKindSystem
        - NamespaceKindProfile
        - NamespaceKindCaRoot
        - NamespaceKindCaInt
        - NamespaceKindServicePrincipal
        - NamespaceKindGroup
        - NamespaceKindDevice
        - NamespaceKindUser
        - NamespaceKindApplication
    RequestDiagnostics:
      type: object
      properties:
        requestHeaders:
          type: array
          items:
            $ref: "#/components/schemas/RequestHeaderEntry"
        serviceRuntime:
          $ref: "#/components/schemas/ServiceRuntimeInfo"
      required:
        - requestHeaders
        - serviceRuntime
    RequestHeaderEntry:
      type: object
      properties:
        key:
          type: string
        value:
          type: array
          items:
            type: string
      required:
        - key
        - value
    ResourceIdentifier:
      type: string
      x-go-type: identifierWithKind[ResourceKind]
    ResourceKind:
      type: string
      enum:
        - reserved
        - ca-root
        - ca-int
        - ms-graph
        - cert-template
        - cert
        - latest-cert-for-template
        - agent-config
      x-enum-varnames:
        - ResourceKindReserved
        - ResourceKindCaRoot
        - ResourceKindCaInt
        - ResourceKindMsGraph
        - ResourceKindCertTemplate
        - ResourceKindCert
        - ResourceKindLatestCertForTemplate
        - ResourceKindAgentConfig
    ResourceLocator:
      type: string
      x-go-type: locator[NamespaceKind, ResourceKind]
    ResourceRef:
      type: object
      properties:
        id:
          x-go-name: ID
          $ref: "#/components/schemas/Identifier"
        locator:
          $ref: "#/components/schemas/ResourceLocator"
        updated:
          description: Time when the resoruce was last updated
          type: string
          format: date-time
        updatedBy:
          type: string
        deleted:
          description: Time when the deleted was deleted
          type: string
          format: date-time
        metadata:
          type: object
          additionalProperties: true
          x-go-type-skip-optional-pointer: true
      required:
        - id
        - locator
    ServiceRuntimeInfo:
      type: object
      properties:
        goVersion:
          type: string
        buildId:
          type: string
          x-go-name: BuildID
      required:
        - goVersion
        - buildId
    SubjectAlternativeNames:
      type: object
      properties:
        dnsNames:
          type: array
          items:
            type: string
          x-go-type-skip-optional-pointer: true
        ipAddresses:
          type: array
          items:
            type: string
            x-go-type: net.IP
          x-go-type-skip-optional-pointer: true
        emails:
          type: array
          items:
            type: string
          x-go-type-skip-optional-pointer: true
    TemplatedCertificateTag:
      type: string
      enum:
        - latest
        - primary
        - secondary
      x-enum-varnames:
        - CertificateTagLatest
        - CertificateTagPrimary
        - CertificateTagSecondary
    WellknownCertificateTemplateName:
      type: string
      enum:
        - default
        - default-intranet-access
        - default-ms-entra-client-creds
        - default-mtls
      x-enum-varnames:
        - CertTemplateNameDefault
        - CertTemplateNameDefaultIntranetAccess
        - CertTemplateNameDefaultMsEntraClientCreds
        - CertTemplateNameDefaultMtls
