openapi: 3.0.3
info:
  title: Small KMS Shared Models
  version: 0.1.2
servers:
  - url: https://example.com
    description: Local server
paths:
  /v1/{namespaceKind}/{namespaceId}/key-policies:
    parameters:
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceKindParameter"
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceIdParameter"
    get:
      tags:
        - admin
      operationId: ListKeyPolicies
      summary: List key policies
      responses:
        200:
          description: List of key specs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/KeyPolicyRef"
  /v1/{namespaceKind}/{namespaceId}/key-policies/{resourceId}:
    parameters:
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceKindParameter"
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceIdParameter"
      - $ref: "oapi-base.yaml#/components/parameters/ResourceIdParameter"
    get:
      tags:
        - admin
      operationId: GetKeyPolicy
      summary: Get key spec
      responses:
        200:
          $ref: "#/components/responses/KeyPolicyResponse"
  /v1/{namespaceKind}/{namespaceId}/keys:
    parameters:
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceKindParameter"
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceIdParameter"
    get:
      tags:
        - admin
      operationId: ListKeys
      summary: List keys
      parameters:
        - name: policyId
          in: query
          description: Policy ID
          required: false
          schema:
            type: string
      responses:
        200:
          description: List of keys
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/KeyRef"
  /v1/{namespaceKind}/{namespaceId}/keys/{resourceId}:
    parameters:
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceKindParameter"
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceIdParameter"
      - $ref: "oapi-base.yaml#/components/parameters/ResourceIdParameter"
    get:
      tags:
        - admin
        - agentclient
      operationId: GetKey
      summary: Get key
      responses:
        200:
          $ref: "#/components/responses/KeyResponse"
security:
  - BearerAuth: []
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    JsonWebKeyCurveName:
      type: string
      enum:
        - P-256
        - P-384
        - P-521
      x-enum-varnames:
        - CurveNameP256
        - CurveNameP384
        - CurveNameP521
      x-go-type: cloudkey.JsonWebKeyCurveName
      x-go-type-import:
        name: cloudkey
        path: "github.com/stephenzsy/small-kms/backend/cloud/key"
      x-go-type-skip-optional-pointer: true
    JsonWebKeyOperation:
      type: string
      enum:
        - sign
        - verify
        - encrypt
        - decrypt
        - wrapKey
        - unwrapKey
      x-go-type: cloudkey.JsonWebKeyOperation
      x-go-type-import:
        name: cloudkey
        path: "github.com/stephenzsy/small-kms/backend/cloud/key"
    JsonWebKeyType:
      type: string
      enum:
        - EC
        - RSA
        - oct
      x-go-type: cloudkey.JsonWebKeyType
      x-go-type-import:
        name: cloudkey
        path: "github.com/stephenzsy/small-kms/backend/cloud/key"
      x-go-type-skip-optional-pointer: true
    JsonWebKeySize:
      type: integer
      format: int32
      # enum:
      #   - 2048
      #   - 3072
      #   - 4096
      # x-enum-varnames:
      #   - JsonWebKeySizeRSA2048
      #   - JsonWebKeySizeRSA3072
      #   - JsonWebKeySizeRSA4096
    JsonWebSignatureAlgorithm:
      type: string
      enum:
        - ES256
        - ES384
        - ES512
        - PS256
        - PS384
        - PS512
        - RS256
        - RS384
        - RS512
      x-go-type: cloudkey.JsonWebSignatureAlgorithm
      x-go-type-import:
        name: cloudkey
        path: "github.com/stephenzsy/small-kms/backend/cloud/key"
    KeySpec:
      description: these attributes should mostly confirm to JWK (RFC7517)
      type: object
      properties:
        kty:
          $ref: "#/components/schemas/JsonWebKeyType"
          x-go-name: KeyType
        kid:
          type: string
          x-go-name: KeyID
        crv:
          $ref: "#/components/schemas/JsonWebKeyCurveName"
          x-go-name: CurveName
        key_size:
          $ref: "#/components/schemas/JsonWebKeySize"
          x-go-name: KeySize
        key_ops:
          type: array
          items:
            $ref: "#/components/schemas/JsonWebKeyOperation"
          x-go-name: KeyOperations
        e:
          description: RSA public exponent
          $ref: "oapi-base.yaml#/components/schemas/Base64RawURLEncodedBytes"
          x-go-name: Exponent
          x-go-type-skip-optional-pointer: true
        n:
          description: RSA modulus
          $ref: "oapi-base.yaml#/components/schemas/Base64RawURLEncodedBytes"
          x-go-name: Modulus
          x-go-type-skip-optional-pointer: true
        x:
          description: X component of an EC public key.
          $ref: "oapi-base.yaml#/components/schemas/Base64RawURLEncodedBytes"
          x-go-name: X
          x-go-type-skip-optional-pointer: true
        y:
          description: Y component of an EC public key.
          $ref: "oapi-base.yaml#/components/schemas/Base64RawURLEncodedBytes"
          x-go-name: Y
          x-go-type-skip-optional-pointer: true
      required:
        - kty
        - key_ops
    SigningKeySpec:
      allOf:
        - $ref: "#/components/schemas/KeySpec"
        - type: object
          properties:
            alg:
              $ref: "#/components/schemas/JsonWebSignatureAlgorithm"
              x-go-name: SignatureAlgorithm
            x5c:
              description: Base64 encoded certificate chain
              type: array
              items:
                $ref: "oapi-base.yaml#/components/schemas/Base64RawURLEncodedBytes"
              x-go-name: CertificateChain
              x-go-type-skip-optional-pointer: true
            x5t:
              $ref: "oapi-base.yaml#/components/schemas/Base64RawURLEncodedBytes"
              x-go-name: ThumbprintSHA1
            x5t#S256:
              $ref: "oapi-base.yaml#/components/schemas/Base64RawURLEncodedBytes"
              x-go-name: ThumbprintSHA256
    JsonWebSignatureKey:
      allOf:
        - $ref: "#/components/schemas/JsonWebKey"
        - type: object
          properties:
            alg:
              $ref: "#/components/schemas/JsonWebSignatureAlgorithm"
              x-go-name: SignatureAlgorithm
          required:
            - alg
        - x-go-type: cloudkey.JsonWebKey
          x-go-type-import:
            name: cloudkey
            path: "github.com/stephenzsy/small-kms/backend/cloud/key"
    JsonWebKey:
      type: object
      properties:
        kty:
          $ref: "#/components/schemas/JsonWebKeyType"
          x-go-name: KeyType
        kid:
          type: string
          x-go-name: KeyID
        key_ops:
          type: array
          items:
            $ref: "#/components/schemas/JsonWebKeyOperation"
          x-go-name: KeyOperations
          x-go-type-skip-optional-pointer: true
        crv:
          $ref: "#/components/schemas/JsonWebKeyCurveName"
          x-go-name: CurveName
        n:
          description: RSA modulus
          $ref: "oapi-base.yaml#/components/schemas/Base64RawURLEncodedBytes"
          x-go-name: Modulus
          x-go-type-skip-optional-pointer: true
        e:
          description: RSA public exponent
          $ref: "oapi-base.yaml#/components/schemas/Base64RawURLEncodedBytes"
          x-go-name: Exponent
          x-go-type-skip-optional-pointer: true
        x:
          description: X component of an EC public key.
          $ref: "oapi-base.yaml#/components/schemas/Base64RawURLEncodedBytes"
          x-go-name: X
          x-go-type-skip-optional-pointer: true
        y:
          description: Y component of an EC public key.
          $ref: "oapi-base.yaml#/components/schemas/Base64RawURLEncodedBytes"
          x-go-name: Y
          x-go-type-skip-optional-pointer: true
        x5u:
          type: string
        x5c:
          description: Base64 encoded certificate chain
          type: array
          items:
            $ref: "oapi-base.yaml#/components/schemas/Base64RawURLEncodedBytes"
          x-go-name: CertificateChain
          x-go-type-skip-optional-pointer: true
        x5t:
          $ref: "oapi-base.yaml#/components/schemas/Base64RawURLEncodedBytes"
          x-go-name: ThmbprintSHA1
        x5t#S256:
          description: SHA-256 fingerprint of the certificate
          $ref: "oapi-base.yaml#/components/schemas/Base64RawURLEncodedBytes"
          x-go-name: ThumbprintSHA256
      required:
        - kty
      x-go-type: cloudkey.JsonWebKey
      x-go-type-import:
        name: cloudkey
        path: "github.com/stephenzsy/small-kms/backend/cloud/key"
    KeyRef:
      allOf:
        - $ref: "oapi-base.yaml#/components/schemas/ResourceReference"
        - $ref: "#/components/schemas/KeyRefFields"
        - x-go-type: keyRefComposed
    KeyRefFields:
      type: object
      properties:
        iat:
          $ref: "oapi-base.yaml#/components/schemas/NumericDate"
          x-go-name: Created
        exp:
          $ref: "oapi-base.yaml#/components/schemas/NumericDate"
          x-go-name: NotAfter
      required:
        - iat
    Key:
      allOf:
        - $ref: "#/components/schemas/KeyRef"
        - $ref: "#/components/schemas/KeyFields"
        - $ref: "#/components/schemas/JsonWebKey"
        - x-go-type: keyComposed
      required:
        - kid
        - kty
    KeyFields:
      type: object
      properties:
        policy:
          $ref: "oapi-base.yaml#/components/schemas/ResourceLocator"
        key_size:
          $ref: "#/components/schemas/JsonWebKeySize"
          x-go-name: KeySize
        iat:
          $ref: "oapi-base.yaml#/components/schemas/NumericDate"
          x-go-name: Created
        nbf:
          $ref: "oapi-base.yaml#/components/schemas/NumericDate"
          x-go-name: NotBefore
      required:
        - policy
        - iat
    KeyPolicyRef:
      allOf:
        - $ref: "oapi-base.yaml#/components/schemas/ResourceReference"
        - $ref: "#/components/schemas/KeyPolicyRefFields"
        - x-go-type: keyPolicyRefComposed
    KeyPolicyRefFields:
      properties:
        displayName:
          type: string
      required:
        - displayName
    KeyPolicy:
      allOf:
        - $ref: "#/components/schemas/KeyPolicyRef"
        - $ref: "#/components/schemas/KeyPolicyFields"
        - x-go-type: keyPolicyComposed
    KeyPolicyFields:
      type: object
      properties:
        keyProperties:
          $ref: "#/components/schemas/GenerateJsonWebKeyProperties"
        exportable:
          type: boolean
        expiryTime:
          $ref: "oapi-base.yaml#/components/schemas/Period"
        # lifetimeActions:
        #   type: array
        #   items:
        #     $ref: "#/components/schemas/LifetimeAction"
        #   x-go-type-skip-optional-pointer: true
      required:
        - keyProperties
        - exportable
    GenerateJsonWebKeyProperties:
      type: object
      properties:
        kty:
          $ref: "#/components/schemas/JsonWebKeyType"
          x-go-name: KeyType
          x-go-type-skip-optional-pointer: true
        crv:
          $ref: "#/components/schemas/JsonWebKeyCurveName"
          x-go-name: CurveName
          x-go-type-skip-optional-pointer: true
        key_size:
          $ref: "#/components/schemas/JsonWebKeySize"
          x-go-name: KeySize
        key_ops:
          type: array
          items:
            $ref: "#/components/schemas/JsonWebKeyOperation"
          x-go-name: KeyOperations
          x-go-type-skip-optional-pointer: true
    KeyPolicyParameters:
      type: object
      properties:
        displayName:
          type: string
          x-go-type-skip-optional-pointer: true
        keyProperties:
          $ref: "#/components/schemas/GenerateJsonWebKeyProperties"
        exportable:
          type: boolean
        expiryTime:
          $ref: "oapi-base.yaml#/components/schemas/Period"
        # lifetimeActions:
        #   type: array
        #   items:
        #     $ref: "#/components/schemas/LifetimeAction"
        #   x-go-type-skip-optional-pointer: true
    LifetimeAction:
      type: object
      properties:
        trigger:
          $ref: "#/components/schemas/LifetimeTrigger"
      required:
        - trigger
    LifetimeTrigger:
      type: object
      properties:
        timeAfterCreate:
          $ref: "oapi-base.yaml#/components/schemas/Period"
        timeBeforeExpiry:
          $ref: "oapi-base.yaml#/components/schemas/Period"
        percentageAfterCreate:
          type: integer
          format: int32
  responses:
    KeyPolicyResponse:
      description: Key policy response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/KeyPolicy"
    KeyResponse:
      description: Key response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Key"
