openapi: 3.0.3
info:
  title: Small KMS Agent APIs
  version: 0.1.2
servers:
  - url: https://example.com
    description: Local server
paths:
  /v1/{namespaceKind}/{namespaceIdentifier}/agent/instance/{resourceIdentifier}/diagnostics:
    parameters:
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceKindParameter"
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceIdentifierParameter"
      - $ref: "oapi-base.yaml#/components/parameters/ResourceIdentifierParameter"
      - $ref: "#/components/parameters/DelegatedAuthorizationHeaderParameter"
    get:
      tags:
        - admin
        - agent
      summary: Get agent diagnostics
      operationId: GetAgentDiagnostics
      responses:
        "200":
          description: Diagnostics response
          content:
            application/json:
              schema:
                $ref: "oapi-base.yaml#/components/schemas/RequestDiagnostics"
  /v1/{namespaceKind}/{namespaceIdentifier}/agent/instance/{resourceIdentifier}/docker/containers:
    parameters:
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceKindParameter"
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceIdentifierParameter"
      - $ref: "oapi-base.yaml#/components/parameters/ResourceIdentifierParameter"
      - $ref: "#/components/parameters/DelegatedAuthorizationHeaderParameter"
    get:
      tags:
        - agent
        - admin
      description: List docker containers
      operationId: AgentDockerContainerList
      responses:
        200:
          description: Container list result
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DockerContainer"
  /v1/{namespaceKind}/{namespaceIdentifier}/agent/instance/{resourceIdentifier}/docker/containers/{containerId}:
    parameters:
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceKindParameter"
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceIdentifierParameter"
      - $ref: "oapi-base.yaml#/components/parameters/ResourceIdentifierParameter"
      - $ref: "#/components/parameters/DelegatedAuthorizationHeaderParameter"
      - name: containerId
        in: path
        description: Container ID
        required: true
        schema:
          type: string
    get:
      tags:
        - agent
        - admin
      description: Inspect docker container
      operationId: AgentDockerContainerInspect
      responses:
        200:
          description: Container inspect result
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DockerContainerJSON"
  /v1/{namespaceKind}/{namespaceIdentifier}/agent/instance/{resourceIdentifier}/docker/images:
    parameters:
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceKindParameter"
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceIdentifierParameter"
      - $ref: "oapi-base.yaml#/components/parameters/ResourceIdentifierParameter"
      - $ref: "#/components/parameters/DelegatedAuthorizationHeaderParameter"
    get:
      tags:
        - agent
        - admin
      description: List docker images
      operationId: AgentDockerImageList
      responses:
        200:
          description: ImageList
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DockerImageSummary"
  /v1/{namespaceKind}/{namespaceIdentifier}/agent/instance/{resourceIdentifier}/docker/info:
    parameters:
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceKindParameter"
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceIdentifierParameter"
      - $ref: "oapi-base.yaml#/components/parameters/ResourceIdentifierParameter"
      - $ref: "#/components/parameters/DelegatedAuthorizationHeaderParameter"
    get:
      tags:
        - agent
        - admin
      description: Get docker system info
      operationId: AgentDockerInfo
      responses:
        200:
          description: DockerInfo
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DockerInfo"
  /v1/{namespaceKind}/{namespaceIdentifier}/agent/instance/{resourceIdentifier}/pull-image:
    parameters:
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceKindParameter"
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceIdentifierParameter"
      - $ref: "oapi-base.yaml#/components/parameters/ResourceIdentifierParameter"
      - $ref: "#/components/parameters/DelegatedAuthorizationHeaderParameter"
    post:
      tags:
        - agent
        - admin
      description: Agent pull image
      operationId: AgentPullImage
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PullImageRequest"
      responses:
        204:
          description: agent pull image resposne
          content: {}
security:
  - BearerAuth: []
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    DelegatedAuthorizationHeaderParameter:
      in: header
      name: "X-Cryptocat-Proxy-Authorization"
      schema:
        type: string
      required: false
  schemas:
    DockerContainer:
      type: object
      x-go-type: types.Container
      x-go-type-import:
        path: "github.com/docker/docker/api/types"
    DockerContainerJSON:
      type: object
      x-go-type: types.ContainerJSON
      x-go-type-import:
        path: "github.com/docker/docker/api/types"
    DockerInfo:
      type: object
      x-go-type: types.Info
      x-go-type-import:
        path: "github.com/docker/docker/api/types"
    DockerImageSummary:
      type: object
      x-go-type: types.ImageSummary
      x-go-type-import:
        path: "github.com/docker/docker/api/types"
    PullImageRequest:
      type: object
      properties:
        imageTag:
          type: string
        includeLatestTag:
          type: boolean
      required:
        - imageTag
