openapi: 3.0.3
info:
  title: Small KMS Shared Managed App Models
  version: 0.1.2
servers:
  - url: https://example.com
    description: Local server
security:
  - BearerAuth: []
paths: {}
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Base64RawURLEncodedBytes:
      type: string
      x-go-type: base64RawURLEncodedBytesImpl
      x-go-type-skip-optional-pointer: true
    Identifier:
      type: string
      x-go-type: identifier
    NamespaceKind:
      type: string
      enum:
        - profile
        - root-ca
        - int-ca
        - service-principal
      x-enum-varnames:
        - NamespaceKindProfile
        - NamespaceKindRootCA
        - NamespaceKindIntermediateCA
        - NamespaceKindServicePrincipal
    ResourceKind:
      type: string
      enum:
        - managed-app
        - root-ca
        - int-ca
        - service-principal
        - cert-policy
        - cert
        - key-policy
        - ns-config
      x-enum-varnames:
        - ProfileResourceKindManagedApp
        - ProfileResourceKindRootCA
        - ProfileResourceKindIntermediateCA
        - ProfileResourceKindServicePrincipal
        - ResourceKindCertPolicy
        - ResourceKindCert
        - ResourceKindKeyPolicy
        - ResourceKindNamespaceConfig
    NumericDate:
      type: integer
      format: int64
      x-go-type: jwt.NumericDate
      x-go-type-import:
        path: github.com/golang-jwt/jwt/v5
    Period:
      type: string
      x-go-type: periodImpl
    ResourceUniqueIdentifier:
      type: string
      x-go-type: DocFullIdentifier
    ResourceReference:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/Identifier"
          x-go-name: ID
        updated:
          type: string
          format: date-time
        deleted:
          type: string
          format: date-time
        updatedBy:
          type: string
      required:
        - id
        - uid
        - updated
  parameters:
    NamespaceKindParameter:
      in: path
      name: namespaceKind
      required: true
      schema:
        $ref: "#/components/schemas/NamespaceKind"
    NamespaceIdentifierParameter:
      in: path
      name: namespaceIdentifier
      required: true
      schema:
        $ref: "#/components/schemas/Identifier"
    ResourceIdentifierParameter:
      in: path
      name: resourceIdentifier
      required: true
      schema:
        $ref: "#/components/schemas/Identifier"
