openapi: 3.0.3
info:
  title: Small KMS Admin API
  version: 0.1.1
servers:
  - url: https://example.com
    description: Local server
security:
  - BearerAuth: []
paths:
  /v1/managed-app:
    $ref: "oapi-managed-app.yaml#/paths/~1v1~1managed-app"
  /v1/managed-app/{managedAppId}:
    $ref: "oapi-managed-app.yaml#/paths/~1v1~1managed-app~1{managedAppId}"
  /v1/{namespaceKind}/{namespaceId}/agent-config/server:
    $ref: "oapi-managed-app.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1agent-config~1server"
  /v1/{namespaceKind}/{namespaceId}/agent-config/{configName}/role-assignments:
    $ref: "oapi-managed-app.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1agent-config~1{configName}~1role-assignments"
  /v1/{namespaceKind}/{namespaceId}/agent-config/radius:
    $ref: "oapi-managed-app.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1agent-config~1radius"
  /v1/{namespaceKind}/{namespaceId}/agent/instance:
    $ref: "oapi-managed-app.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1agent~1instance"
  /v1/{namespaceKind}/{namespaceId}/agent/instance/{resourceId}:
    $ref: "oapi-managed-app.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1agent~1instance~1{resourceId}"
  /v1/{namespaceKind}/{namespaceId}/agent/instance/{resourceId}/proxy-auth/token:
    $ref: "oapi-managed-app.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1agent~1instance~1{resourceId}~1proxy-auth~1token"
  /v1/{namespaceKind}/{namespaceId}/agent/instance/{resourceId}/config/radius:
    $ref: "oapi-agent-push.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1agent~1instance~1{resourceId}~1config~1radius"
  /v1/{namespaceKind}/{namespaceId}/agent/instance/{resourceId}/docker/containers:
    $ref: "oapi-agent-push.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1agent~1instance~1{resourceId}~1docker~1containers"
  /v1/{namespaceKind}/{namespaceId}/agent/instance/{resourceId}/docker/containers/{containerId}:
    $ref: "oapi-agent-push.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1agent~1instance~1{resourceId}~1docker~1containers~1{containerId}"
  /v1/{namespaceKind}/{namespaceId}/agent/instance/{resourceId}/docker/containers/{containerId}/stop:
    $ref: "oapi-agent-push.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1agent~1instance~1{resourceId}~1docker~1containers~1{containerId}~1stop"
  /v1/{namespaceKind}/{namespaceId}/agent/instance/{resourceId}/pull-image:
    $ref: "oapi-agent-push.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1agent~1instance~1{resourceId}~1pull-image"
  /v1/{namespaceKind}/{namespaceId}/agent/instance/{resourceId}/launch-agent:
    $ref: "oapi-agent-push.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1agent~1instance~1{resourceId}~1launch-agent"
  /v1/{namespaceKind}/{namespaceId}/certificates:
    $ref: "oapi-cert.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1certificates"
  /v1/{namespaceKind}/{namespaceId}/certificates/{resourceId}:
    $ref: "oapi-cert.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1certificates~1{resourceId}"
  /v1/{namespaceKind}/{namespaceId}/cert-policy:
    $ref: "oapi-cert.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1cert-policy"
  /v1/{namespaceKind}/{namespaceId}/cert-policy/{resourceId}:
    $ref: "oapi-cert.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1cert-policy~1{resourceId}"
  /v1/{namespaceKind}/{namespaceId}/cert-rule/issuer:
    $ref: "oapi-cert.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1cert-rule~1issuer"
  /v1/{namespaceKind}/{namespaceId}/cert-policy/{resourceId}/keyvault-role-assignments/{resourceCategory}:
    $ref: "oapi-cert.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1cert-policy~1{resourceId}~1keyvault-role-assignments~1{resourceCategory}"
  /v1/{namespaceKind}/{namespaceId}/key-policies:
    $ref: "oapi-key.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1key-policies"
  /v1/{namespaceKind}/{namespaceId}/secret-policies:
    $ref: "oapi-secret.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1secret-policies"
  /v1/{namespaceKind}/{namespaceId}/secret-policies/{resourceId}:
    $ref: "oapi-secret.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1secret-policies~1{resourceId}"
  /v1/{namespaceKind}/{namespaceId}/secret-policies/{resourceId}/generate:
    $ref: "oapi-secret.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1secret-policies~1{resourceId}~1generate"
  /v1/{namespaceKind}/{namespaceId}/secrets:
    $ref: "oapi-secret.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1secrets"
  /v1/{namespaceKind}/{namespaceId}/secrets/{resourceId}:
    $ref: "oapi-secret.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1secrets~1{resourceId}"
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
