openapi: 3.0.3
info:
  title: Small KMS Shared Models
  version: 0.1.2
servers:
  - url: https://example.com
    description: Local server
paths:
  /v1/profile/{profileResourceKind}/{namespaceId}:
    parameters:
      - $ref: "#/components/parameters/ProfileResourceKindParameter"
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceIdParameter"
    get:
      tags:
        - admin
      operationId: GetProfile
      summary: Get profile
      responses:
        200:
          $ref: "#/components/responses/ProfileResponse"
    put:
      tags:
        - admin
      operationId: PutProfile
      summary: Put profile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProfileParameters"
      responses:
        200:
          $ref: "#/components/responses/ProfileResponse"
  /v1/profile/{profileResourceKind}/{namespaceId}/import:
    parameters:
      - $ref: "#/components/parameters/ProfileResourceKindParameter"
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceIdParameter"
    post:
      tags:
        - admin
      operationId: ImportProfile
      summary: Import profile
      responses:
        200:
          $ref: "#/components/responses/ProfileResponse"
  /v1/{namespaceKind}/{namespaceId}/groupMemberOf/{groupId}:
    parameters:
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceKindParameter"
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceIdParameter"
      - name: groupId
        in: path
        description: Group ID
        required: true
        schema:
          type: string
          format: uuid
    post:
      tags:
        - admin
      operationId: SyncGroupMemberOf
      summary: Sync group memberOf
      responses:
        204:
          description: No response
          content: {}
  /v1/{namespaceKind}/{namespaceId}/groupMemberOf:
    parameters:
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceKindParameter"
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceIdParameter"
    get:
      tags:
        - admin
      operationId: ListGroupMemberOf
      summary: List group memberOf
      responses:
        200:
          $ref: "oapi-base.yaml#/components/responses/ResourceReferenceListResponse"
security:
  - BearerAuth: []
components:
  parameters:
    ProfileResourceKindParameter:
      name: profileResourceKind
      in: path
      description: Profile resource kind
      required: true
      schema:
        $ref: "oapi-base.yaml#/components/schemas/ResourceKind"
  schemas:
    ProfileRef:
      allOf:
        - $ref: "oapi-base.yaml#/components/schemas/ResourceReference"
        - $ref: "#/components/schemas/ProfileRefFields"
        - x-go-type: profileRefComposed
    ProfileRefFields:
      type: object
      properties:
        displayName:
          type: string
      required:
        - displayName
    Profile:
      $ref: "#/components/schemas/ProfileRef"
    ProfileParameters:
      type: object
      properties:
        displayName:
          type: string
  responses:
    ProfileResponse:
      description: OK
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Profile"
