openapi: 3.0.3
info:
  title: Small KMS Shared Managed App Models
  version: 0.1.2
servers:
  - url: https://example.com
    description: Local server
security:
  - BearerAuth: []
paths: {}
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Identifier:
      type: string
      x-go-type: identifierImpl
    NamespaceKind:
      type: string
      enum:
        - profile
        - root-ca
      x-enum-varnames:
        - NamespaceKindProfile
        - NamespaceKindRootCA
    NumericDate:
      type: integer
      format: int64
      x-go-type: jwt.NumericDate
      x-go-type-import:
        path: github.com/golang-jwt/jwt/v5
    Period:
      type: string
      x-go-type: periodImpl        
    ResourceKind:
      type: string
      enum:
        - managed-app
        - root-ca
        - key-spec
      x-enum-varnames:
        - ProfileResourceKindManagedApp
        - ProfileResourceKindRootCA
        - ResourceKindKeySpec
    ResourceReference:
      type: object
      properties:
        _nid:
          type: string
          format: uuid
          x-go-name: NID
        _rid:
          type: string
          format: uuid
          x-go-name: RID
        namespaceKind:
          $ref: "#/components/schemas/NamespaceKind"
        namespaceIdentifier:
          $ref: "#/components/schemas/Identifier"
        resourceKind:
          $ref: "#/components/schemas/ResourceKind"
        resourceIdentifier:
          $ref: "#/components/schemas/Identifier"
        updated:
          type: string
          format: date-time
        deleted:
          type: string
          format: date-time
        updatedBy:
          type: string
      required:
        - _nid
        - _rid
        - namespaceKind
        - namespaceIdentifier
        - resourceKind
        - resourceIdentifier
        - updated
        - updatedBy
  parameters:
    NamespaceKindParameter:
      in: path
      name: namespaceKind
      required: true
      schema:
        $ref: "#/components/schemas/NamespaceKind"
    NamespaceIdentifierParameter:
      in: path
      name: namespaceIdentifier
      required: true
      schema:
        $ref: "#/components/schemas/Identifier"
    ResourceIdentifierParameter:
      in: path
      name: resourceIdentifier
      required: true
      schema:
        $ref: "#/components/schemas/Identifier"
