openapi: 3.0.3
info:
  title: Small KMS Admin API
  version: 0.1.1
servers:
  - url: https://example.com
    description: Local server
security:
  - BearerAuth: []
paths:
  /v1/{namespaceKind}/{namespaceId}/certificates/{resourceId}:
    $ref: "oapi-cert.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1certificates~1{resourceId}"
  /v1/{namespaceKind}/{namespaceId}/cert-policy/{resourceId}/enroll-cert:
    $ref: "oapi-cert.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1cert-policy~1{resourceId}~1enroll-cert"
  /v1/{namespaceKind}/{namespaceId}/keys/{resourceId}:
    $ref: "oapi-key.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1keys~1{resourceId}"
  /v1/{namespaceKind}/{namespaceId}/secrets/{resourceId}:
    $ref: "oapi-secret.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1secrets~1{resourceId}"
  /v1/{namespaceKind}/{namespaceId}/agent-config/server:
    $ref: "oapi-managed-app.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1agent-config~1server"
  /v1/{namespaceKind}/{namespaceId}/agent-config/radius:
    $ref: "oapi-managed-app.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1agent-config~1radius"
  /v1/{namespaceKind}/{namespaceId}/agent/instance/{resourceId}:
    $ref: "oapi-managed-app.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1agent~1instance~1{resourceId}"
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    EnrollCertificateRequest:
      $ref: "oapi-cert.yaml#/components/schemas/EnrollCertificateRequest"
    Certificate:
      $ref: "oapi-cert.yaml#/components/schemas/Certificate"
    AgentConfigServer:
      $ref: "oapi-managed-app.yaml#/components/schemas/AgentConfigServer"
    AgentConfigRadius:
      $ref: "oapi-managed-app.yaml#/components/schemas/AgentConfigRadius"
    AgentInstanceFields:
      $ref: "oapi-managed-app.yaml#/components/schemas/AgentInstanceFields"
    Secret:
      $ref: "oapi-secret.yaml#/components/schemas/Secret"
  responses:
    CertificateResponse:
      description: Key spec reponse
      content:
        application/json:
          schema:
            $ref: "oapi-cert.yaml#/components/schemas/Certificate"
    AgentConfigRadiusResponse:
      description: Agent radius config response
      content:
        application/json:
          schema:
            $ref: "oapi-managed-app.yaml#/components/schemas/AgentConfigRadius"
    KeyResponse:
      description: Key response
      content:
        application/json:
          schema:
            $ref: "oapi-key.yaml#/components/schemas/Key"
