openapi: 3.0.3
info:
  title: Small KMS Admin API
  version: 0.1.1
servers:
  - url: https://example.com
    description: Local server
security:
  - BearerAuth: []
paths:
  /v1/diagnostics:
    $ref: "oapi-base.yaml#/paths/~1v1~1diagnostics"
  /v1/managed-app:
    $ref: "oapi-managed-app.yaml#/paths/~1v1~1managed-app"
  /v1/managed-app/{managedAppId}:
    $ref: "oapi-managed-app.yaml#/paths/~1v1~1managed-app~1{managedAppId}"
  /v1/system-app/{systemAppName}:
    $ref: "oapi-managed-app.yaml#/paths/~1v1~1system-app~1{systemAppName}"
  /v1/{namespaceKind}/{namespaceId}/agent-config/server:
    $ref: "oapi-managed-app.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1agent-config~1server"
  /v1/{namespaceKind}/{namespaceId}/agent-config/server/role-assignments:
    $ref: "oapi-managed-app.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1agent-config~1server~1role-assignments"
  /v1/{namespaceKind}/{namespaceId}/agent/instance:
    $ref: "oapi-managed-app.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1agent~1instance"
  /v1/{namespaceKind}/{namespaceId}/agent/instance/{resourceId}:
    $ref: "oapi-managed-app.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1agent~1instance~1{resourceId}"
  /v1/{namespaceKind}/{namespaceId}/agent/instance/{resourceId}/proxy-auth/token:
    $ref: "oapi-managed-app.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1agent~1instance~1{resourceId}~1proxy-auth~1token"
  /v1/{namespaceKind}/{namespaceId}/agent/instance/{resourceId}/diagnostics:
    $ref: "oapi-agent-push.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1agent~1instance~1{resourceId}~1diagnostics"
  /v1/{namespaceKind}/{namespaceId}/agent/instance/{resourceId}/docker/containers:
    $ref: "oapi-agent-push.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1agent~1instance~1{resourceId}~1docker~1containers"
  /v1/{namespaceKind}/{namespaceId}/agent/instance/{resourceId}/docker/containers/{containerId}:
    $ref: "oapi-agent-push.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1agent~1instance~1{resourceId}~1docker~1containers~1{containerId}"
  /v1/{namespaceKind}/{namespaceId}/agent/instance/{resourceId}/docker/containers/{containerId}/stop:
    $ref: "oapi-agent-push.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1agent~1instance~1{resourceId}~1docker~1containers~1{containerId}~1stop"
  /v1/{namespaceKind}/{namespaceId}/agent/instance/{resourceId}/docker/images:
    $ref: "oapi-agent-push.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1agent~1instance~1{resourceId}~1docker~1images"
  /v1/{namespaceKind}/{namespaceId}/agent/instance/{resourceId}/docker/info:
    $ref: "oapi-agent-push.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1agent~1instance~1{resourceId}~1docker~1info"
  /v1/{namespaceKind}/{namespaceId}/agent/instance/{resourceId}/docker/networks:
    $ref: "oapi-agent-push.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1agent~1instance~1{resourceId}~1docker~1networks"
  /v1/{namespaceKind}/{namespaceId}/agent/instance/{resourceId}/pull-image:
    $ref: "oapi-agent-push.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1agent~1instance~1{resourceId}~1pull-image"
  /v1/{namespaceKind}/{namespaceId}/agent/instance/{resourceId}/launch-agent:
    $ref: "oapi-agent-push.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1agent~1instance~1{resourceId}~1launch-agent"
  /v1/profile/{profileResourceKind}:
    $ref: "oapi-profile.yaml#/paths/~1v1~1profile~1{profileResourceKind}"
  /v1/profile/{profileResourceKind}/{namespaceId}:
    $ref: "oapi-profile.yaml#/paths/~1v1~1profile~1{profileResourceKind}~1{namespaceId}"
  /v1/profile/{profileResourceKind}/{namespaceId}/import:
    $ref: "oapi-profile.yaml#/paths/~1v1~1profile~1{profileResourceKind}~1{namespaceId}~1import"
  /v1/{namespaceKind}/{namespaceId}/groupMemberOf:
    $ref: "oapi-profile.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1groupMemberOf"
  /v1/{namespaceKind}/{namespaceId}/groupMemberOf/{groupId}:
    $ref: "oapi-profile.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1groupMemberOf~1{groupId}"
  /v1/{namespaceKind}/{namespaceId}/cert:
    $ref: "oapi-cert.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1cert"
  /v1/{namespaceKind}/{namespaceId}/cert/{resourceId}:
    $ref: "oapi-cert.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1cert~1{resourceId}"
  /v1/{namespaceKind}/{namespaceId}/cert-policy:
    $ref: "oapi-cert.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1cert-policy"
  /v1/{namespaceKind}/{namespaceId}/cert-policy/{resourceId}:
    $ref: "oapi-cert.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1cert-policy~1{resourceId}"
  /v1/{namespaceKind}/{namespaceId}/cert-policy/{resourceId}/create-cert:
    $ref: "oapi-cert.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1cert-policy~1{resourceId}~1create-cert"
  /v1/{namespaceKind}/{namespaceId}/cert-policy/{resourceId}/enroll-cert:
    $ref: "oapi-cert.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1cert-policy~1{resourceId}~1enroll-cert"
  /v1/{namespaceKind}/{namespaceId}/cert-rule/issuer:
    $ref: "oapi-cert.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1cert-rule~1issuer"
  /v1/{namespaceKind}/{namespaceId}/cert-rule/ms-entra-client-credential:
    $ref: "oapi-cert.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1cert-rule~1ms-entra-client-credential"
  /v1/{namespaceKind}/{namespaceId}/cert-policy/{resourceId}/keyvault-role-assignments/{resourceCategory}:
    $ref: "oapi-cert.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1cert-policy~1{resourceId}~1keyvault-role-assignments~1{resourceCategory}"
  /v1/{namespaceKind}/{namespaceId}/secret-policies:
    $ref: "oapi-secret.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1secret-policies"
  /v1/{namespaceKind}/{namespaceId}/secret-policies/{resourceId}:
    $ref: "oapi-secret.yaml#/paths/~1v1~1{namespaceKind}~1{namespaceId}~1secret-policies~1{resourceId}"
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
