openapi: 3.0.3
info:
  title: Small KMS Admin API
  version: 0.1.1
servers:
  - url: https://example.com
    description: Local server
security:
  - BearerAuth: []
paths:
  /v1/{namespaceKind}/{namespaceIdentifier}/secret-policies:
    parameters:
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceKindParameter"
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceIdentifierParameter"
    get:
      tags:
        - admin
      operationId: ListSecretPolicies
      summary: List secret policies
      responses:
        200:
          description: List of secret policies
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SecretPolicyRef"
  /v1/{namespaceKind}/{namespaceIdentifier}/secret-policies/{resourceIdentifier}:
    parameters:
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceKindParameter"
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceIdentifierParameter"
      - $ref: "oapi-base.yaml#/components/parameters/ResourceIdentifierParameter"
    get:
      tags:
        - admin
      operationId: GetSecretPolicy
      summary: Get key spec
      responses:
        200:
          $ref: "#/components/responses/SecretPolicyResponse"
    put:
      tags:
        - admin
      operationId: PutSecretPolicy
      summary: Put key spec
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SecretPolicyParameters"
      responses:
        200:
          $ref: "#/components/responses/SecretPolicyResponse"
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    SecretPolicyRef:
      allOf:
        - $ref: "oapi-base.yaml#/components/schemas/ResourceReference"
        - $ref: "#/components/schemas/SecretPolicyRefFields"
        - x-go-type: secretPolicyRefComposed
    SecretPolicyRefFields:
      properties:
        displayName:
          type: string
      required:
        - displayName
    SecretRandomCharacterClass:
      type: string
      enum:
        #- alpha-numeric
        #- base64
        - base64-raw-url
        #- hex
      x-enum-varnames:
        #- SecretRandomCharClassAlphaNumeric
        #- SecretRandomCharClassBase64
        - SecretRandomCharClassBase64RawURL
        #- SecretRandomCharClassHexadecimal
    SecretGenerateMode:
      type: string
      enum:
        - manual
        - random-server
      x-enum-varnames:
        - SecretGenerateModeManual
        - SecretGenerateModeServerGeneratedRandom
    SecretPolicyParameters:
      properties:
        displayName:
          type: string
          x-go-type-skip-optional-pointer: true
        mode:
          $ref: "#/components/schemas/SecretGenerateMode"
        randomCharacterClass:
          $ref: "#/components/schemas/SecretRandomCharacterClass"
          x-go-type-skip-optional-pointer: true
        randomLength:
          type: integer
          minimum: 8
        expiryTime:
          $ref: "oapi-base.yaml#/components/schemas/Period"
      required:
        - mode
    SecretPolicy:
      allOf:
        - $ref: "#/components/schemas/SecretPolicyRef"
        - $ref: "#/components/schemas/SecretPolicyFields"
        - x-go-type: secretPolicyComposed
    SecretPolicyFields:
      properties:
        mode:
          $ref: "#/components/schemas/SecretGenerateMode"
        randomCharacterClass:
          $ref: "#/components/schemas/SecretRandomCharacterClass"
          x-go-type-skip-optional-pointer: true
        randomLength:
          description: Length of encoded random secret, in bytes
          type: integer
          minimum: 8
        expiryTime:
          $ref: "oapi-base.yaml#/components/schemas/Period"
      required:
        - mode
  responses:
    SecretPolicyResponse:
      description: Secret policy reponse
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/SecretPolicy"
