openapi: 3.0.3
info:
  title: Small KMS Admin API
  version: 0.1.1
servers:
  - url: https://example.com
    description: Local server
security:
  - BearerAuth: []
paths:
  /v1/diagnostics:
    $ref: "oapi-base.yaml#/paths/~1v1~1diagnostics"
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    RequestDiagnostics:
      $ref: "oapi-base.yaml#/components/schemas/RequestDiagnostics"
  responses:
    CertificateResponse:
      description: Key spec reponse
      content:
        application/json:
          schema:
            $ref: "oapi-cert.yaml#/components/schemas/Certificate"
