openapi: 3.0.3
info:
  title: Small KMS Agent APIs
  version: 0.1.2
servers:
  - url: https://example.com
    description: Local server
paths:
  /v1/{namespaceKind}/{namespaceId}/agent/instance/{resourceId}/docker/containers:
    parameters:
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceKindParameter"
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceIdParameter"
      - $ref: "oapi-base.yaml#/components/parameters/ResourceIdParameter"
      - $ref: "#/components/parameters/DelegatedAuthorizationHeaderParameter"
    get:
      tags:
        - agent
        - admin
      description: List docker containers
      operationId: AgentDockerContainerList
      responses:
        200:
          description: Container list result
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DockerContainer"
  /v1/{namespaceKind}/{namespaceId}/agent/instance/{resourceId}/docker/containers/{containerId}:
    parameters:
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceKindParameter"
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceIdParameter"
      - $ref: "oapi-base.yaml#/components/parameters/ResourceIdParameter"
      - $ref: "#/components/parameters/DelegatedAuthorizationHeaderParameter"
      - name: containerId
        in: path
        description: Container ID
        required: true
        schema:
          type: string
    get:
      tags:
        - agent
        - admin
      description: Inspect docker container
      operationId: AgentDockerContainerInspect
      responses:
        200:
          description: Container inspect result
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DockerContainerJSON"
    delete:
      tags:
        - agent
        - admin
      description: Remove docker container
      operationId: AgentDockerContainerRemove
      responses:
        204:
          description: Container remove result
          content: {}
  /v1/{namespaceKind}/{namespaceId}/agent/instance/{resourceId}/docker/containers/{containerId}/stop:
    parameters:
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceKindParameter"
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceIdParameter"
      - $ref: "oapi-base.yaml#/components/parameters/ResourceIdParameter"
      - $ref: "#/components/parameters/DelegatedAuthorizationHeaderParameter"
      - name: containerId
        in: path
        description: Container ID
        required: true
        schema:
          type: string
    post:
      tags:
        - agent
        - admin
      description: Stop docker container
      operationId: AgentDockerContainerStop
      responses:
        204:
          description: Container stop result
          content: {}
  /v1/{namespaceKind}/{namespaceId}/agent/instance/{resourceId}/docker/images:
    parameters:
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceKindParameter"
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceIdParameter"
      - $ref: "oapi-base.yaml#/components/parameters/ResourceIdParameter"
      - $ref: "#/components/parameters/DelegatedAuthorizationHeaderParameter"
    get:
      tags:
        - agent
        - admin
      description: List docker images
      operationId: AgentDockerImageList
      responses:
        200:
          description: ImageList
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DockerImageSummary"
  /v1/{namespaceKind}/{namespaceId}/agent/instance/{resourceId}/docker/networks:
    parameters:
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceKindParameter"
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceIdParameter"
      - $ref: "oapi-base.yaml#/components/parameters/ResourceIdParameter"
      - $ref: "#/components/parameters/DelegatedAuthorizationHeaderParameter"
    get:
      tags:
        - agent
        - admin
      description: Get docker system info
      operationId: AgentDockerNetworkList
      responses:
        200:
          description: List of networks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DockerNetworkResource"
  /v1/{namespaceKind}/{namespaceId}/agent/instance/{resourceId}/pull-image:
    parameters:
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceKindParameter"
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceIdParameter"
      - $ref: "oapi-base.yaml#/components/parameters/ResourceIdParameter"
      - $ref: "#/components/parameters/DelegatedAuthorizationHeaderParameter"
    post:
      tags:
        - agent
        - admin
      description: Agent pull image
      operationId: AgentPullImage
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PullImageRequest"
      responses:
        204:
          description: agent pull image resposne
          content: {}
  /v1/{namespaceKind}/{namespaceId}/agent/instance/{resourceId}/launch-agent:
    parameters:
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceKindParameter"
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceIdParameter"
      - $ref: "oapi-base.yaml#/components/parameters/ResourceIdParameter"
      - $ref: "#/components/parameters/DelegatedAuthorizationHeaderParameter"
    post:
      tags:
        - agent
        - admin
      description: Launch agent
      operationId: AgentLaunchAgent
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LaunchAgentRequest"
      responses:
        201:
          $ref: "#/components/responses/DockerContianerCreateResponse"
  /v1/{namespaceKind}/{namespaceId}/agent/instance/{resourceId}/config/radius:
    parameters:
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceKindParameter"
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceIdParameter"
      - $ref: "oapi-base.yaml#/components/parameters/ResourceIdParameter"
      - $ref: "#/components/parameters/DelegatedAuthorizationHeaderParameter"
    post:
      tags:
        - agent
        - admin
      description: Push agent radius configuration
      operationId: PushAgentConfigRadius
      responses:
        204:
          description: Radius config push result
          content: {}
security:
  - BearerAuth: []
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    DelegatedAuthorizationHeaderParameter:
      in: header
      name: "X-Cryptocat-Proxy-Authorization"
      schema:
        type: string
      required: false
  schemas:
    DockerContainer:
      type: object
      x-go-type: types.Container
      x-go-type-import:
        path: "github.com/docker/docker/api/types"
    DockerContainerJSON:
      type: object
      x-go-type: types.ContainerJSON
      x-go-type-import:
        path: "github.com/docker/docker/api/types"
    DockerImageSummary:
      type: object
      x-go-type: types.ImageSummary
      x-go-type-import:
        path: "github.com/docker/docker/api/types"
    DockerNetworkResource:
      type: object
      x-go-type: types.NetworkResource
      x-go-type-import:
        path: "github.com/docker/docker/api/types"
    LaunchAgentRequest:
      type: object
      properties:
        mode:
          $ref: "oapi-managed-app.yaml#/components/schemas/AgentMode"
        containerName:
          type: string
        imageTag:
          type: string
        listenerAddress:
          example: ":10443"
          type: string
        pushEndpoint:
          type: string
        msEntraIdClientCertSecretName:
          type: string
          x-go-type-skip-optional-pointer: true
        exposedPortSpecs:
          type: array
          items:
            type: string
            example: "10443/tcp"
        hostBinds:
          type: array
          items:
            type: string
            example: "/var/run/docker.sock:/var/run/docker.sock:rw"
        secrets:
          type: array
          items:
            $ref: "oapi-managed-app.yaml#/components/schemas/SecretMount"
        networkName:
          type: string
          x-go-type-skip-optional-pointer: true
        env:
          type: array
          items:
            type: string
            example: "FOO=BAR"
          x-go-type-skip-optional-pointer: true
      required:
        - mode
        - containerName
        - imageTag
        - listenerAddress
        - pushEndpoint
        - exposedPortSpecs
        - hostBinds
        - secrets
    PullImageRequest:
      type: object
      properties:
        imageRepo:
          type: string
          x-go-type-skip-optional-pointer: true
        imageTag:
          type: string
        includeLatestTag:
          type: boolean
      required:
        - imageTag
  responses:
    DockerContianerCreateResponse:
      description: Docker container create response
      content:
        application/json:
          schema:
            type: object
            x-go-type: container.CreateResponse
            x-go-type-import:
              path: "github.com/docker/docker/api/types/container"
