openapi: 3.0.3
info:
  title: Small KMS Shared Models
  version: 0.1.2
servers:
  - url: https://example.com
    description: Local server
paths:
  /v1/{namespaceKind}/{namespaceIdentifier}/cert:
    parameters:
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceKindParameter"
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceIdentifierParameter"
    get:
      tags:
        - admin
      operationId: ListCertificates
      summary: List certificates
      parameters:
        - name: policyId
          in: query
          description: Policy ID
          required: false
          schema:
            type: string
      responses:
        200:
          description: List of cert specs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CertificateRef"
  /v1/{namespaceKind}/{namespaceIdentifier}/cert/{resourceIdentifier}:
    parameters:
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceKindParameter"
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceIdentifierParameter"
      - $ref: "oapi-base.yaml#/components/parameters/ResourceIdentifierParameter"
    get:
      tags:
        - admin
      operationId: GetCertificate
      summary: Get certificate
      responses:
        200:
          $ref: "#/components/responses/CertificateResponse"
    delete:
      tags:
        - admin
      operationId: DeleteCertificate
      summary: Delete certificate
      responses:
        204:
          description: Certificate deleted
          content: {}
  /v1/{namespaceKind}/{namespaceIdentifier}/cert-policy:
    parameters:
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceKindParameter"
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceIdentifierParameter"
    get:
      tags:
        - admin
      operationId: ListCertPolicies
      summary: List cert policies
      responses:
        200:
          description: List of cert specs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CertPolicyRef"
  /v1/{namespaceKind}/{namespaceIdentifier}/cert-policy/{resourceIdentifier}:
    parameters:
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceKindParameter"
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceIdentifierParameter"
      - $ref: "oapi-base.yaml#/components/parameters/ResourceIdentifierParameter"
    get:
      tags:
        - admin
      operationId: GetCertPolicy
      summary: Get cert policy
      responses:
        200:
          $ref: "#/components/responses/CertPolicyResponse"
    put:
      tags:
        - admin
      operationId: PutCertPolicy
      summary: Put cert policy
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CertPolicyParameters"
      responses:
        200:
          $ref: "#/components/responses/CertPolicyResponse"
  /v1/{namespaceKind}/{namespaceIdentifier}/cert-policy/{resourceIdentifier}/create-cert:
    parameters:
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceKindParameter"
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceIdentifierParameter"
      - $ref: "oapi-base.yaml#/components/parameters/ResourceIdentifierParameter"
    post:
      tags:
        - admin
      operationId: CreateCertificate
      summary: Create certificate
      responses:
        201:
          $ref: "#/components/responses/CertificateResponse"
  /v1/{namespaceKind}/{namespaceIdentifier}/cert-policy/{resourceIdentifier}/issuer-cert:
    parameters:
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceKindParameter"
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceIdentifierParameter"
      - $ref: "oapi-base.yaml#/components/parameters/ResourceIdentifierParameter"
    post:
      tags:
        - admin
      operationId: SetIssuerCertificate
      summary: Set issuer certificate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PolicyIssuerCertRequest"
      responses:
        204:
          description: Issuer certificate set
          content: {}
  /v1/{namespaceKind}/{namespaceIdentifier}/cert-policy/{resourceIdentifier}/enroll-ms-entra-client-credential:
    parameters:
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceKindParameter"
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceIdentifierParameter"
      - $ref: "oapi-base.yaml#/components/parameters/ResourceIdentifierParameter"
    post:
      tags:
        - admin
        - agentclient
      operationId: EnrollMsEntraClientCredential
      summary: Set issuer certificate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EnrollMsEntraClientCredentialRequest"
      responses:
        200:
          $ref: "#/components/responses/CertificateResponse"
security:
  - BearerAuth: []
components:
  schemas:
    CertificateFlag:
      type: string
      enum:
        - ca
        - rootCa
        - serverAuth
        - clientAuth
      x-enum-varnames:
        - CertificateFlagCA
        - CertificateFlagRootCA
        - CertificateFlagServerAuth
        - CertificateFlagClientAuth
    CertPolicyRef:
      allOf:
        - $ref: "oapi-base.yaml#/components/schemas/ResourceReference"
        - $ref: "#/components/schemas/CertPolicyRefFields"
        - x-go-type: certPolicyRefComposed
    CertPolicyRefFields:
      properties:
        displayName:
          type: string
      required:
        - displayName
    CertPolicy:
      allOf:
        - $ref: "#/components/schemas/CertPolicyRef"
        - $ref: "#/components/schemas/CertPolicyFields"
        - x-go-type: certPolicyComposed
    CertPolicyFields:
      properties:
        issuerPolicy:
          $ref: "oapi-base.yaml#/components/schemas/ResourceLocator"
        keySpec:
          $ref: "oapi-key.yaml#/components/schemas/SigningKeySpec"
        keyExportable:
          type: boolean
        expiryTime:
          $ref: "oapi-base.yaml#/components/schemas/Period"
        lifetimeAction:
          $ref: "oapi-key.yaml#/components/schemas/LifetimeAction"
        subject:
          $ref: "#/components/schemas/CertificateSubject"
        subjectAlternativeNames:
          $ref: "#/components/schemas/SubjectAlternativeNames"
        flags:
          type: array
          items:
            $ref: "#/components/schemas/CertificateFlag"
        version:
          type: string
          x-go-type: HexDigest
      required:
        - issuerPolicy
        - keySpec
        - keyExportable
        - expiryTime
        - subject
        - certificateFlags
        - flags
        - version
    CertPolicyParameters:
      type: object
      properties:
        displayName:
          type: string
        keySpec:
          $ref: "oapi-key.yaml#/components/schemas/SigningKeySpec"
        keyExportable:
          type: boolean
        expiryTime:
          $ref: "oapi-base.yaml#/components/schemas/Period"
        lifetimeAction:
          $ref: "oapi-key.yaml#/components/schemas/LifetimeAction"
        subject:
          $ref: "#/components/schemas/CertificateSubject"
        subjectAlternativeNames:
          $ref: "#/components/schemas/SubjectAlternativeNames"
        flags:
          type: array
          items:
            $ref: "#/components/schemas/CertificateFlag"
          x-go-type-skip-optional-pointer: true
        issuerPolicy:
          $ref: "oapi-base.yaml#/components/schemas/ResourceLocator"
      required:
        - expiryTime
        - subject
        - issuerTemplate
    CertificateSubject:
      type: object
      properties:
        commonName:
          type: string
      required:
        - commonName
    SubjectAlternativeNames:
      type: object
      properties:
        dnsNames:
          type: array
          items:
            type: string
          x-go-type-skip-optional-pointer: true
          x-go-name: DNSNames
        ipAddresses:
          type: array
          items:
            type: string
            x-go-type: net.IP
          x-go-type-skip-optional-pointer: true
          x-go-name: IPAddresses
        emails:
          type: array
          items:
            type: string
          x-go-type-skip-optional-pointer: true
    CertificateRef:
      allOf:
        - $ref: "oapi-base.yaml#/components/schemas/ResourceReference"
        - $ref: "#/components/schemas/CertificateRefFields"
        - x-go-type: certificateRefComposed
    CertificateAttributes:
      allOf:
        - $ref: "oapi-key.yaml#/components/schemas/KeyAttributes"
        - type: object
          properties:
            issuer:
              $ref: "oapi-base.yaml#/components/schemas/SLocator"
    CertificateRefFields:
      type: object
      properties:
        thumbprint:
          type: string
        attributes:
          $ref: "#/components/schemas/CertificateAttributes"
        issuerForPolicy:
          $ref: "oapi-base.yaml#/components/schemas/SLocator"
      required:
        - thumbprint
        - attributes
    Certificate:
      allOf:
        - $ref: "#/components/schemas/CertificateRef"
        - $ref: "#/components/schemas/CertificateFields"
        - x-go-type: certificateComposed
    CertificateFields:
      type: object
      properties:
        subject:
          $ref: "#/components/schemas/CertificateSubject"
        subjectAlternativeNames:
          $ref: "#/components/schemas/SubjectAlternativeNames"
        flags:
          type: array
          items:
            $ref: "#/components/schemas/CertificateFlag"
          x-go-type-skip-optional-pointer: true
        alg:
          $ref: "oapi-key.yaml#/components/schemas/JsonWebKeySignatureAlgorithm"
        x5u:
          type: string
        x5c:
          description: Base64 encoded certificate chain
          type: array
          items:
            $ref: "oapi-base.yaml#/components/schemas/Base64RawURLEncodedBytes"
          x-go-name: CertificateChain
          x-go-type-skip-optional-pointer: true
        x5t:
          $ref: "oapi-base.yaml#/components/schemas/Base64RawURLEncodedBytes"
          x-go-name: ThmbprintSHA1
        x5t#S256:
          description: SHA-256 fingerprint of the certificate
          $ref: "oapi-base.yaml#/components/schemas/Base64RawURLEncodedBytes"
          x-go-name: ThumbprintSHA256
      required:
        - subject
        - alg
        - x5t
        - x5t#S256
    EnrollMsEntraClientCredentialRequest:
      type: object
      properties:
        publicKey:
          $ref: "oapi-key.yaml#/components/schemas/JsonWebKey"
        msEntraProof:
          type: string
        force:
          description: Force enrollment, will clear existing credential on graph, initial enrollment must be forced
          type: boolean
      required:
        - publicKey
        - msEntraProof
    PolicyIssuerCertRequest:
      type: object
      properties:
        issuerId:
          $ref: "oapi-base.yaml#/components/schemas/Identifier"
      required:
        - issuerId
  responses:
    CertPolicyResponse:
      description: Key spec reponse
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/CertPolicy"
    CertificateResponse:
      description: Key spec reponse
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Certificate"
