openapi: 3.0.3
info:
  title: Small KMS Shared Models
  version: 0.1.2
servers:
  - url: https://example.com
    description: Local server
paths:
  /v1/profile/{profileResourceKind}:
    parameters:
      - $ref: "#/components/parameters/ProfileResourceKindParameter"
    get:
      tags:
        - admin
      operationId: ListProfiles
      summary: List profiles
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ProfileRef"
  /v1/profile/{profileResourceKind}/{namespaceIdentifier}:
    parameters:
      - $ref: "#/components/parameters/ProfileResourceKindParameter"
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceIdentifierParameter"
    get:
      tags:
        - admin
      operationId: GetProfile
      summary: Get profile
      responses:
        200:
          $ref: "#/components/responses/ProfileResponse"
    put:
      tags:
        - admin
      operationId: PutProfile
      summary: Put profile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProfileParameters"
      responses:
        200:
          $ref: "#/components/responses/ProfileResponse"
  /v1/profile/{profileResourceKind}/{namespaceIdentifier}/import:
    parameters:
      - $ref: "#/components/parameters/ProfileResourceKindParameter"
      - $ref: "oapi-base.yaml#/components/parameters/NamespaceIdentifierParameter"
    post:
      tags:
        - admin
      operationId: ImportProfile
      summary: Import profile
      responses:
        200:
          $ref: "#/components/responses/ProfileResponse"          
security:
  - BearerAuth: []
components:
  parameters:
    ProfileResourceKindParameter:
      name: profileResourceKind
      in: path
      description: Profile resource kind
      required: true
      schema:
        $ref: "oapi-base.yaml#/components/schemas/ResourceKind"
  schemas:
    ProfileRef:
      allOf:
        - $ref: "oapi-base.yaml#/components/schemas/ResourceReference"
        - $ref: "#/components/schemas/ProfileRefFields"
        - x-go-type: profileRefComposed
    ProfileRefFields:
      type: object
      properties:
        displayName:
          type: string
      required:
        - displayName
    Profile:
      $ref: "#/components/schemas/ProfileRef"
    ProfileParameters:
      type: object
      properties:
        displayName:
          type: string
  responses:
    ProfileResponse:
      description: OK
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Profile"
