openapi: 3.0.3
info:
  title: Small KMS Shared Managed App Models
  version: 0.1.2
servers:
  - url: https://example.com
    description: Local server
security:
  - BearerAuth: []
paths: {}
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Identifier:
      type: string
      x-go-type: identifierImpl
    NamespaceKind:
      type: string
      enum:
        - profile
      x-enum-varnames:
        - NamespaceKindProfile
    ResourceKind:
      type: string
      enum:
        - managed-app
      x-enum-varnames:
        - ResourceKindManagedApp
    ResourceMetadata:
      type: object
      properties:
        updated:
          type: string
          format: date-time
        deleted:
          type: string
          format: date-time
        updatedBy:
          type: string
      required:
        - updated
    ResourceReference:
      type: object
      properties:
        _nid:
          type: string
          format: uuid
          x-go-name: NID
        _rid:
          type: string
          format: uuid
          x-go-name: RID
        namespaceKind:
          $ref: "#/components/schemas/NamespaceKind"
        namespaceIdentifier:
          $ref: "#/components/schemas/Identifier"
        resourceKind:
          $ref: "#/components/schemas/ResourceKind"
        resourceIdentifier:
          $ref: "#/components/schemas/Identifier"
        updated:
          type: string
          format: date-time
        deleted:
          type: string
          format: date-time
        updatedBy:
          type: string
      required:
        - _nid
        - _rid
        - namespaceKind
        - namespaceIdentifier
        - resourceKind
        - resourceIdentifier
        - updated
        - updatedBy
