openapi: 3.0.3
info:
  title: Small KMS Shared Managed App Models
  version: 0.1.2
servers:
  - url: https://example.com
    description: Local server
security:
  - BearerAuth: []
paths: {}
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Base64RawURLEncodedBytes:
      type: string
      x-go-type: base64RawURLEncodedBytesImpl
    Identifier:
      type: string
      x-go-type: identifierImpl
    NamespaceKind:
      type: string
      enum:
        - profile
        - root-ca
        - int-ca
        - service-principal
      x-enum-varnames:
        - NamespaceKindProfile
        - NamespaceKindRootCA
        - NamespaceKindIntermediateCA
        - NamespaceKindServicePrincipal
    NumericDate:
      type: integer
      format: int64
      x-go-type: jwt.NumericDate
      x-go-type-import:
        path: github.com/golang-jwt/jwt/v5
    Period:
      type: string
      x-go-type: periodImpl
    ResourceKind:
      type: string
      enum:
        - managed-app
        - root-ca
        - int-ca
        - service-principal
        - cert-policy
        - cert
        - cert-link
        - key-policy
      x-enum-varnames:
        - ProfileResourceKindManagedApp
        - ProfileResourceKindRootCA
        - ProfileResourceKindIntermediateCA
        - ProfileResourceKindServicePrincipal
        - ResourceKindCertPolicy
        - ResourceKindCert
        - ResourceKindCertLink
        - ResourceKindKeyPolicy
    SLocator:
      type: string
      x-go-type: storageLocator
    ResourceLocator:
      type: object
      properties:
        namespaceKind:
          $ref: "#/components/schemas/NamespaceKind"
        namespaceIdentifier:
          $ref: "#/components/schemas/Identifier"
        resourceKind:
          $ref: "#/components/schemas/ResourceKind"
        resourceIdentifier:
          $ref: "#/components/schemas/Identifier"
      required:
        - namespaceKind
        - namespaceIdentifier
        - resourceKind
        - resourceIdentifier
    ResourceReference:
      allOf:
        - type: object
          properties:
            _id:
              $ref: "#/components/schemas/SLocator"
              x-go-name: LocatorID
          required:
            - _id
        - $ref: "#/components/schemas/ResourceLocator"
        - type: object
          properties:
            updated:
              type: string
              format: date-time
            deleted:
              type: string
              format: date-time
            updatedBy:
              type: string
          required:
            - updated
            - updatedBy
  parameters:
    NamespaceKindParameter:
      in: path
      name: namespaceKind
      required: true
      schema:
        $ref: "#/components/schemas/NamespaceKind"
    NamespaceIdentifierParameter:
      in: path
      name: namespaceIdentifier
      required: true
      schema:
        $ref: "#/components/schemas/Identifier"
    ResourceIdentifierParameter:
      in: path
      name: resourceIdentifier
      required: true
      schema:
        $ref: "#/components/schemas/Identifier"
