openapi: 3.0.3
info:
  title: Small KMS Admin API
  version: 0.1.0
servers:
  - url: http://localhost:9000
    description: Local server
paths:
  /v1/{namespaceId}/certificates:
    get:
      tags:
        - certs
      summary: List certificates
      operationId: ListCertificatesV1
      parameters:
        - in: path
          name: namespaceId
          schema:
            type: string
            format: uuid
          required: true
      responses:
        "200":
          description: A JSON array of Certificate Refs
          content:
            application/json:
              schema:
                title: ListCertificatesResponse
                type: array
                items:
                  $ref: "#/components/schemas/CertificateRef"
  /v1/{namespaceId}/certificates/{id}:
    get:
      tags:
        - certs
      summary: Get certificate
      operationId: GetCertificateV1
      parameters:
        - in: path
          name: namespaceId
          schema:
            type: string
            format: uuid
          required: true
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          required: true
        - in: header
          name: Accept
          schema:
            type: string
            enum:
              - application/json
              - application/x-pem-file
              - application/x-x509-ca-cert
            x-enum-varnames:
              - Accept_Json
              - Accept_Pem
              - Accept_X509CaCert
      responses:
        "200":
          description: Get certificate response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CertificateRef"
            application/x-pem-file:
              schema:
                type: string
                format: binary
            application/x-x509-ca-cert:
              schema:
                type: string
                format: binary
  /v1/{namespaceId}/profile:
    parameters:
      - in: path
        description: AAD directory object ID
        name: namespaceId
        schema:
          type: string
          format: uuid
        required: true
    get:
      tags:
        - directory
      summary: Get namespace profile
      operationId: GetNamespaceProfileV1
      responses:
        "200":
          description: Get namespace resposne profile
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NamespaceProfile"
    post:
      tags:
        - directory
      summary: Register namespace
      operationId: RegisterNamespaceProfileV1
      responses:
        "200":
          description: register namespace profile response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NamespaceProfile"
  /v1/namespaces/{namespaceType}:
    get:
      tags:
        - directory
      summary: List namespaces
      operationId: ListNamespacesV1
      parameters:
        - in: path
          name: namespaceType
          schema:
            $ref: "#/components/schemas/NamespaceType"
          required: true
      responses:
        "200":
          description: List namespace response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/NamespaceRef"
  /v1/my/profiles:
    get:
      tags:
        - user
      summary: Get my profiles
      operationId: GetMyProfilesV1
      responses:
        "200":
          description: Get my profiles info response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/NamespaceProfile"
  /v1/{namespaceId}/policies:
    get:
      tags:
        - policy
      summary: List policies
      operationId: ListPoliciesV1
      parameters:
        - in: path
          name: namespaceId
          schema:
            type: string
            format: uuid
          required: true
      responses:
        "200":
          description: List policies response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PolicyRef"
  /v1/{namespaceId}/policies/{policyId}:
    put:
      tags:
        - policy
      summary: Put Policy
      operationId: PutPolicyV1
      parameters:
        - in: path
          name: namespaceId
          schema:
            type: string
            format: uuid
          required: true
        - in: path
          name: policyId
          schema:
            type: string
            format: uuid
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PolicyParameters"
        required: true
      responses:
        "200":
          description: Certificate policy
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Policy"
        400:
          $ref: "#/components/responses/ErrorResponse"
    get:
      tags:
        - policy
      summary: Get Certificate Policy
      operationId: GetPolicyV1
      parameters:
        - in: path
          name: namespaceId
          schema:
            type: string
            format: uuid
          required: true
        - in: path
          name: policyId
          schema:
            type: string
            format: uuid
          required: true
      responses:
        "200":
          description: Certificate policy
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Policy"
        404:
          $ref: "#/components/responses/ErrorResponse"
  /v1/{namespaceId}/policies/{policyId}/apply:
    post:
      tags:
        - policy
      summary: Apply policy
      operationId: ApplyPolicyV1
      parameters:
        - in: path
          name: namespaceId
          schema:
            type: string
            format: uuid
          required: true
        - in: path
          name: policyId
          schema:
            type: string
            format: uuid
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ApplyPolicyRequest"
        required: false
      responses:
        "200":
          description: Create certificate
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PolicyState"
  /v1/diagnostics:
    get:
      tags:
        - diagnostics
      summary: Get diagnostics
      operationId: GetDiagnosticsV1
      responses:
        "200":
          description: Diagnostics response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RequestDiagnostics"
security:
  - BearerAuth: []
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    NamespaceType:
      type: string
      enum:
        - "#builtin.ca.intermediate"
        - "#microsoft.graph.servicePrincipal"
        - "#microsoft.graph.user"
        - "#microsoft.graph.group"
        - "#microsoft.graph.device"
      x-enum-varnames:
        - NamespaceType_BuiltInCaInt
        - NamespaceType_MsGraphServicePrincipal
        - NamespaceType_MsGraphUser
        - NamespaceType_MsGraphGroup
        - NamespaceType_MsGraphDevice
    ApplyPolicyRequest:
      type: object
      properties:
        checkConsistency:
          description: Check consistency of the policy
          type: boolean
        forceRenewCertificate:
          description: Force certificate renewal
          type: boolean
    CertificateSubject:
      type: object
      properties:
        cn:
          description: Common name
          type: string
          x-go-name: CN
        ou:
          description: Organizational unit
          type: string
          x-go-name: OU
        o:
          description: Organization
          type: string
        c:
          description: Country or region
          type: string
      required:
        - cn
    KeyProperties:
      type: object
      properties:
        kty:
          type: string
          enum:
            - RSA
            - EC
          x-enum-varnames:
            - Kty_RSA
            - Kty_EC
          x-go-name: KeyType
        key_size:
          type: integer
          format: int32
          enum:
            - 2048
            - 3072
            - 4096
          x-enum-varnames:
            - KeySize_2048
            - KeySize_3072
            - KeySize_4096
          x-go-name: KeySize
        crv:
          type: string
          enum:
            - P-256
            - P-384
          x-enum-varnames:
            - EcCurve_P256
            - EcCurve_P384
          x-go-name: CurveName
        reuse_key:
          description: Keep using the same key version if exists
          type: boolean
          x-go-name: ReuseKey
      required:
        - kty
    CertificateUsage:
      type: string
      enum:
        - root-ca
        - intermediate-ca
        - server-and-client
        - server-only
        - client-only
      x-enum-varnames:
        - Usage_RootCA
        - Usage_IntCA
        - Usage_ServerAndClient
        - Usage_ServerOnly
        - Usage_ClientOnly
    CertificateRef:
      type: object
      properties:
        namespaceId:
          description: Unique ID of the namespace
          type: string
          format: uuid
          x-go-name: NamespaceID
        id:
          description: Unique ID of the certificate, also the serial number of the certificate
          type: string
          format: uuid
          x-go-name: ID
        name:
          description: Name of the certificate, also the common name (CN) of the certificate
          type: string
        usage:
          $ref: "#/components/schemas/CertificateUsage"
        notAfter:
          description: Expiration date of the certificate
          type: string
          format: date-time
        issuerNamespace:
          description: Issuer of the certificate
          type: string
          format: uuid
        issuer:
          description: Issuer of the certificate
          type: string
          format: uuid
        createdBy:
          description: Unique ID of the user who created the certificate
          type: string
      required:
        - namespaceId
        - id
        - name
        - usage
        - notAfter
        - issuerNamespace
        - issuer
        - createdBy
    PolicyType:
      type: string
      enum:
        # - certIssue
        - certRequest
      x-enum-varnames:
        # - PolicyType_CertIssue
        - PolicyType_CertRequest
    ResourceRef:
      type: object
      properties:
        namespaceId:
          description: Unique ID of the namespace
          type: string
          format: uuid
          x-go-name: NamespaceID
        id:
          type: string
          format: uuid
          x-go-name: ID
        updatedBy:
          description: Unique ID of the user who created the policy
          type: string
        updated:
          description: Time when the policy was last updated
          type: string
          format: date-time
      required:
        - namespaceId
        - id
        - updatedBy
        - updated
    PolicyStateCertRequest:
      type: object
      properties:
        lastCertId:
          type: string
          format: uuid
          x-go-name: LastCertID
        lastCertIssued:
          type: string
          format: date-time
        lastCertExpires:
          type: string
          format: date-time
        lastAction:
          type: string
      required:
        - lastCertId
        - lastCertIssued
        - lastCertExpires
        - lastAction
    PolicyState:
      allOf:
        - $ref: "#/components/schemas/ResourceRef"
        - type: object
          properties:
            policyType:
              $ref: "#/components/schemas/PolicyType"
            status:
              type: string
            message:
              type: string
            certRequest:
              $ref: "#/components/schemas/PolicyStateCertRequest"
          required:
            - policyType
            - string
            - message
    # CertificateIssurancePolicyParameters:
    #   type: object
    #   properties:
    #     issuerId:
    #       description: ID of the current issuer certificate
    #       type: string
    #       format: uuid
    #       x-go-name: IssuerID
    #     allowedRequesters:
    #       type: array
    #       items:
    #         type: string
    #         format: uuid
    #     allowedUsages:
    #       type: array
    #       items:
    #         $ref: "#/components/schemas/CertificateUsage"
    #     max_validity_months:
    #       type: integer
    #       format: int32
    #       x-go-name: MaxValidityInMonths
    #   required:
    #     - issuerId
    CertificateLifetimeTrigger:
      type: object
      properties:
        days_before_expiry:
          x-go-name: DaysBeforeExpiry
          type: integer
          format: int32
        lifetime_percentage:
          x-go-name: LifetimePercentage
          type: integer
          format: int32
    CertificateSubjectAlternativeNames:
      type: object
      properties:
        dns_names:
          x-go-name: DNSNames
          type: array
          items:
            type: string
        emails:
          x-go-name: Emails
          type: array
          items:
            type: string
        upns:
          x-go-name: UserPrincipalNames
          type: array
          items:
            type: string
    CertificateRequestPolicyParameters:
      type: object
      properties:
        issuerNamespaceId:
          description: ID of the issuer namespace
          type: string
          format: uuid
          x-go-name: IssuerNamespaceID
        validity_months:
          x-go-name: ValidityInMonths
          type: integer
          format: int32
        keyStorePath:
          type: string
        keyProperties:
          $ref: "#/components/schemas/KeyProperties"
        subject:
          $ref: "#/components/schemas/CertificateSubject"
        subjectAlternativeNames:
          $ref: "#/components/schemas/CertificateSubjectAlternativeNames"
        usage:
          $ref: "#/components/schemas/CertificateUsage"
        lifetimeTrigger:
          $ref: "#/components/schemas/CertificateLifetimeTrigger"
        msGraphGroupAllowMembers:
          type: boolean
      required:
        - issuerNamespaceId
        - subject
        - usage
        - keyStorePath
    PolicyParameters:
      type: object
      properties:
        policyType:
          $ref: "#/components/schemas/PolicyType"
        # certIssue:
        #   $ref: "#/components/schemas/CertificateIssurancePolicyParameters"
        certRequest:
          $ref: "#/components/schemas/CertificateRequestPolicyParameters"
      required:
        - policyType
    PolicyRef:
      allOf:
        - $ref: "#/components/schemas/ResourceRef"
        - type: object
          title: PolicyRefParameters
          properties:
            policyType:
              $ref: "#/components/schemas/PolicyType"
          required:
            - policyType
    Policy:
      allOf:
        - $ref: "#/components/schemas/PolicyRef"
        - $ref: "#/components/schemas/PolicyParameters"
    NamespaceRef:
      allOf:
        - $ref: "#/components/schemas/ResourceRef"
        - type: object
          properties:
            objectType:
              $ref: "#/components/schemas/NamespaceType"
            displayName:
              type: string
          required:
            - objectType
            - displayName
    NamespaceProfile:
      allOf:
        - $ref: "#/components/schemas/NamespaceRef"
        - type: object
          properties:
            servicePrincipalType:
              type: string
            userPrincipalName:
              type: string
            deviceOwnership:
              type: string
            deviceId:
              description: \#microsoft.graph.device deviceId
              x-go-name: DeviceID
              type: string
              format: uuid
            manufacturer:
              description: \#microsoft.graph.device manufacturer
              type: string
            model:
              description: \#microsoft.graph.device model
              type: string
            operatingSystem:
              description: \#microsoft.graph.device operatingSystem
              type: string
            operatingSystemVersion:
              description: \#microsoft.graph.device operatingSystemVersion
              type: string
            isCompliant:
              description: \#microsoft.graph.device isCompliant
              type: boolean
            registerdOwners:
              type: array
              items:
                $ref: "#/components/schemas/NamespaceRef"
            memberOf:
              type: array
              items:
                $ref: "#/components/schemas/NamespaceRef"
    RequestHeaderEntry:
      type: object
      properties:
        key:
          type: string
        value:
          type: array
          items:
            type: string
      required:
        - key
        - value
    RequestDiagnostics:
      type: object
      properties:
        requestHeaders:
          type: array
          items:
            $ref: "#/components/schemas/RequestHeaderEntry"
        serviceRuntime:
          type: object
          title: ServiceRuntime
          properties:
            goVersion:
              type: string
          required:
            - goVersion
          additionalProperties:
            type: string
      required:
        - requestHeaders
        - serviceRuntime
    MyProfile:
      type: object
      properties:
        user:
          $ref: "#/components/schemas/NamespaceProfile"
        device:
          $ref: "#/components/schemas/NamespaceProfile"
  responses:
    GenericResponse:
      description: generic response
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: string
              message:
                type: string
            additionalProperties: true
    ErrorResponse:
      description: error response
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: string
              message:
                type: string
            additionalProperties: true
