openapi: 3.0.3
info:
  title: Small KMS API
  version: 0.1.0
servers:
  - url: http://localhost:9000
    description: Local server
paths:
  /v1/admin/ca/{id}:
    get:
      tags:
        - admin
      summary: Get CA Certificate Suite
      description: Get CA Certificate Suite
      operationId: AdminGetCACertificateSuite
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Identifier of the CA certificate (e.g. root)
      responses:
        "200":
          description: A JSON array of user names
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CertificateSuite"
    post:
      tags:
        - admin
      summary: Create CA Certificate Suite
      description: Create CA Certificate Suite
      operationId: AdminCreateCACertificateSuite
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Identifier of the CA certificate (e.g. root)
        - in: query
          name: force
          schema:
            type: boolean
            default: false
      requestBody:
        content:
          appliction/json:
            schema:
              $ref: "#/components/schemas/CreateCertificateRequest"
      responses:
        "200":
          description: A JSON array of user names
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CertificateSuite"
components:
  schemas:
    CertificateSuite:
      type: object
      properties:
        id:
          type: string
          x-go-name: ID
      required:
        - id
    CreateCertificateRequest:
      type: object
      properties:
        commonName:
          type: string
        validity:
          type: string
          format: duration
        kty:
          type: string
          enum:
            - RSA
        size:
          type: number
          enum:
            - 4096
      required:
        - cn
        - validity
