// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Cli.Commons.Extensions;
using Microsoft.Kiota.Cli.Commons.IO;
using Microsoft.Kiota.Cli.Commons;
using SmallKms.Client.Models;
using System.Collections.Generic;
using System.CommandLine;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace SmallKms.Client.V2.Item.Item.CertificateTemplates.Item.Certificates.Latest {
    /// <summary>
    /// Builds and executes requests for operations under \v2\{namespaceType}\{namespaceId}\certificate-templates\{templateId}\certificates\latest
    /// </summary>
    public class LatestRequestBuilder : BaseCliRequestBuilder {
        /// <summary>
        /// Get certificate
        /// </summary>
        public Command BuildGetCommand() {
            var command = new Command("get");
            command.Description = "Get certificate";
            var namespaceTypeOption = new Option<string>("--namespace-type") {
            };
            namespaceTypeOption.IsRequired = true;
            command.AddOption(namespaceTypeOption);
            var namespaceIdOption = new Option<string>("--namespace-id") {
            };
            namespaceIdOption.IsRequired = true;
            command.AddOption(namespaceIdOption);
            var templateIdOption = new Option<string>("--template-id") {
            };
            templateIdOption.IsRequired = true;
            command.AddOption(templateIdOption);
            var includeCertificateOption = new Option<string>("--include-certificate") {
            };
            includeCertificateOption.IsRequired = false;
            command.AddOption(includeCertificateOption);
            var outputOption = new Option<FormatterType>("--output", () => FormatterType.JSON){
                IsRequired = true
            };
            command.AddOption(outputOption);
            var queryOption = new Option<string>("--query");
            command.AddOption(queryOption);
            var jsonNoIndentOption = new Option<bool>("--json-no-indent", r => {
                if (bool.TryParse(r.Tokens.Select(t => t.Value).LastOrDefault(), out var value)) {
                    return value;
                }
                return true;
            }, description: "Disable indentation for the JSON output formatter.");
            command.AddOption(jsonNoIndentOption);
            command.SetHandler(async (invocationContext) => {
                var namespaceType = invocationContext.ParseResult.GetValueForOption(namespaceTypeOption);
                var namespaceId = invocationContext.ParseResult.GetValueForOption(namespaceIdOption);
                var templateId = invocationContext.ParseResult.GetValueForOption(templateIdOption);
                var includeCertificate = invocationContext.ParseResult.GetValueForOption(includeCertificateOption);
                var output = invocationContext.ParseResult.GetValueForOption(outputOption);
                var query = invocationContext.ParseResult.GetValueForOption(queryOption);
                var jsonNoIndent = invocationContext.ParseResult.GetValueForOption(jsonNoIndentOption);
                IOutputFilter outputFilter = invocationContext.BindingContext.GetService(typeof(IOutputFilter)) as IOutputFilter ?? throw new ArgumentNullException("outputFilter");
                IOutputFormatterFactory outputFormatterFactory = invocationContext.BindingContext.GetService(typeof(IOutputFormatterFactory)) as IOutputFormatterFactory ?? throw new ArgumentNullException("outputFormatterFactory");
                var cancellationToken = invocationContext.GetCancellationToken();
                var reqAdapter = invocationContext.GetRequestAdapter();
                var requestInfo = ToGetRequestInformation(q => {
                    if (!string.IsNullOrEmpty(includeCertificate)) q.QueryParameters.IncludeCertificate = includeCertificate;
                });
                if (namespaceType is not null) requestInfo.PathParameters.Add("namespaceType", namespaceType);
                if (namespaceId is not null) requestInfo.PathParameters.Add("namespaceId", namespaceId);
                if (templateId is not null) requestInfo.PathParameters.Add("templateId", templateId);
                var response = await reqAdapter.SendPrimitiveAsync<Stream>(requestInfo, errorMapping: default, cancellationToken: cancellationToken) ?? Stream.Null;
                response = (response != Stream.Null) ? await outputFilter.FilterOutputAsync(response, query, cancellationToken) : response;
                var formatterOptions = output.GetOutputFormatterOptions(new FormatterOptionsModel(!jsonNoIndent));
                var formatter = outputFormatterFactory.GetFormatter(output);
                await formatter.WriteOutputAsync(response, formatterOptions, cancellationToken);
            });
            return command;
        }
        /// <summary>
        /// Instantiates a new LatestRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        public LatestRequestBuilder(Dictionary<string, object> pathParameters) : base("{+baseurl}/v2/{namespaceType}/{namespaceId}/certificate-templates/{templateId}/certificates/latest{?includeCertificate*}", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new LatestRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public LatestRequestBuilder(string rawUrl) : base("{+baseurl}/v2/{namespaceType}/{namespaceId}/certificate-templates/{templateId}/certificates/latest{?includeCertificate*}", rawUrl) {
        }
        /// <summary>
        /// Get certificate
        /// </summary>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<LatestRequestBuilderGetQueryParameters>>? requestConfiguration = default) {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<LatestRequestBuilderGetQueryParameters>> requestConfiguration = default) {
#endif
            var requestInfo = new RequestInformation {
                HttpMethod = Method.GET,
                UrlTemplate = UrlTemplate,
                PathParameters = PathParameters,
            };
            requestInfo.Headers.Add("Accept", "application/json");
            if (requestConfiguration != null) {
                var requestConfig = new RequestConfiguration<LatestRequestBuilderGetQueryParameters>();
                requestConfiguration.Invoke(requestConfig);
                requestInfo.AddQueryParameters(requestConfig.QueryParameters);
                requestInfo.AddRequestOptions(requestConfig.Options);
                requestInfo.AddHeaders(requestConfig.Headers);
            }
            return requestInfo;
        }
        /// <summary>
        /// Get certificate
        /// </summary>
        public class LatestRequestBuilderGetQueryParameters {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? IncludeCertificate { get; set; }
#nullable restore
#else
            public string IncludeCertificate { get; set; }
#endif
        }
    }
}
