// Package shared provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package shared

import (
	"time"
)

// Defines values for CertificateUsage.
const (
	CertUsageCA               CertificateUsage = "ca"
	CertUsageCARoot           CertificateUsage = "caRoot"
	CertUsageClientAuth       CertificateUsage = "clientAuth"
	CertUsageKeyNonExportable CertificateUsage = "keyNonExportable"
	CertUsageServerAuth       CertificateUsage = "serverAuth"
)

// Defines values for JwkAlg.
const (
	AlgES256 JwkAlg = "ES256"
	AlgES384 JwkAlg = "ES384"
	AlgRS256 JwkAlg = "RS256"
	AlgRS384 JwkAlg = "RS384"
	AlgRS512 JwkAlg = "RS512"
)

// Defines values for NamespaceKind.
const (
	NamespaceKindApplication      NamespaceKind = "application"
	NamespaceKindCaInt            NamespaceKind = "ca-int"
	NamespaceKindCaRoot           NamespaceKind = "ca-root"
	NamespaceKindDevice           NamespaceKind = "device"
	NamespaceKindGroup            NamespaceKind = "group"
	NamespaceKindProfile          NamespaceKind = "profile"
	NamespaceKindServicePrincipal NamespaceKind = "service-principal"
	NamespaceKindSystem           NamespaceKind = "sys"
	NamespaceKindUser             NamespaceKind = "user"
)

// Defines values for ResourceKind.
const (
	ResourceKindAgentConfig           ResourceKind = "agent-config"
	ResourceKindCaInt                 ResourceKind = "ca-int"
	ResourceKindCaRoot                ResourceKind = "ca-root"
	ResourceKindCert                  ResourceKind = "cert"
	ResourceKindCertTemplate          ResourceKind = "cert-template"
	ResourceKindLatestCertForTemplate ResourceKind = "latest-cert-for-template"
	ResourceKindMsGraph               ResourceKind = "ms-graph"
	ResourceKindReserved              ResourceKind = "reserved"
)

// Defines values for WellknownCertificateTemplateName.
const (
	CertTemplateNameDefault                   WellknownCertificateTemplateName = "default"
	CertTemplateNameDefaultIntranetAccess     WellknownCertificateTemplateName = "default-intranet-access"
	CertTemplateNameDefaultMsEntraClientCreds WellknownCertificateTemplateName = "default-ms-entra-client-creds"
	CertTemplateNameDefaultMtls               WellknownCertificateTemplateName = "default-mtls"
)

// CertificateRef defines model for CertificateRef.
type CertificateRef = certificateRefComposed

// CertificateRefFields defines model for CertificateRefFields.
type CertificateRefFields struct {
	// IsIssued Whether the certificate has been issued
	IsIssued bool `json:"isIssued"`

	// NotAfter Expiration date of the certificate
	NotAfter time.Time `json:"notAfter"`

	// SubjectCommonName Common name
	SubjectCommonName string          `json:"subjectCommonName"`
	Template          ResourceLocator `json:"template"`

	// Thumbprint X.509 certificate SHA-1 thumbprint
	Thumbprint string `json:"thumbprint"`
}

// CertificateUsage defines model for CertificateUsage.
type CertificateUsage string

// Identifier defines model for Identifier.
type Identifier = identifierImpl

// JwkAlg defines model for JwkAlg.
type JwkAlg string

// NamespaceIdentifier defines model for NamespaceIdentifier.
type NamespaceIdentifier = identifierWithKind[NamespaceKind]

// NamespaceKind defines model for NamespaceKind.
type NamespaceKind string

// ResourceIdentifier defines model for ResourceIdentifier.
type ResourceIdentifier = identifierWithKind[ResourceKind]

// ResourceKind defines model for ResourceKind.
type ResourceKind string

// ResourceLocator defines model for ResourceLocator.
type ResourceLocator = locator[NamespaceKind, ResourceKind]

// ResourceRef defines model for ResourceRef.
type ResourceRef struct {
	// Deleted Time when the deleted was deleted
	Deleted  *time.Time             `json:"deleted,omitempty"`
	Id       Identifier             `json:"id"`
	Locator  ResourceLocator        `json:"locator"`
	Metadata map[string]interface{} `json:"metadata,omitempty"`

	// Updated Time when the resoruce was last updated
	Updated   *time.Time `json:"updated,omitempty"`
	UpdatedBy *string    `json:"updatedBy,omitempty"`
}

// WellknownCertificateTemplateName defines model for WellknownCertificateTemplateName.
type WellknownCertificateTemplateName string
