// Package shared provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package shared

import (
	"net"
	"time"
)

// Defines values for JwkAlg.
const (
	AlgES256 JwkAlg = "ES256"
	AlgES384 JwkAlg = "ES384"
	AlgRS256 JwkAlg = "RS256"
	AlgRS384 JwkAlg = "RS384"
	AlgRS512 JwkAlg = "RS512"
)

// Defines values for JwtKty.
const (
	KeyTypeEC  JwtKty = "EC"
	KeyTypeRSA JwtKty = "RSA"
)

// Defines values for NamespaceKind.
const (
	NamespaceKindApplication      NamespaceKind = "application"
	NamespaceKindCaInt            NamespaceKind = "ca-int"
	NamespaceKindCaRoot           NamespaceKind = "ca-root"
	NamespaceKindDevice           NamespaceKind = "device"
	NamespaceKindGroup            NamespaceKind = "group"
	NamespaceKindManagedApp       NamespaceKind = "managed-app"
	NamespaceKindProfile          NamespaceKind = "profile"
	NamespaceKindServicePrincipal NamespaceKind = "service-principal"
	NamespaceKindUser             NamespaceKind = "user"
)

// Defines values for ResourceKind.
const (
	AgentCallback             ResourceKind = "agent-callback"
	ResourceKindAgentCallback ResourceKind = "agent-config"
	ResourceKindAgentConfig   ResourceKind = "latest-cert-for-template"
	ResourceKindApp           ResourceKind = "app"
	ResourceKindCaInt         ResourceKind = "ca-int"
	ResourceKindCaRoot        ResourceKind = "ca-root"
	ResourceKindCert          ResourceKind = "cert"
	ResourceKindCertTemplate  ResourceKind = "cert-template"
	ResourceKindMsGraph       ResourceKind = "ms-graph"
	ResourceKindReserved      ResourceKind = "reserved"
)

// Defines values for TemplatedCertificateTag.
const (
	CertificateTagLatest    TemplatedCertificateTag = "latest"
	CertificateTagPrimary   TemplatedCertificateTag = "primary"
	CertificateTagSecondary TemplatedCertificateTag = "secondary"
)

// Defines values for WellknownCertificateTemplateName.
const (
	CertTemplateNameDefault                   WellknownCertificateTemplateName = "default"
	CertTemplateNameDefaultIntranetAccess     WellknownCertificateTemplateName = "default-intranet-access"
	CertTemplateNameDefaultMsEntraClientCreds WellknownCertificateTemplateName = "default-ms-entra-client-creds"
	CertTemplateNameDefaultMtls               WellknownCertificateTemplateName = "default-mtls"
)

// CertificateRef defines model for CertificateRef.
type CertificateRef = certificateRefComposed

// CertificateRefFields defines model for CertificateRefFields.
type CertificateRefFields struct {
	// IsIssued Whether the certificate has been issued
	IsIssued bool `json:"isIssued"`

	// NotAfter Expiration date of the certificate
	NotAfter time.Time `json:"notAfter"`

	// SubjectCommonName Common name
	SubjectCommonName string          `json:"subjectCommonName"`
	Template          ResourceLocator `json:"template"`
}

// Identifier defines model for Identifier.
type Identifier = identifierImpl

// JwkAlg defines model for JwkAlg.
type JwkAlg string

// JwkProperties Property bag of JSON Web Key (RFC 7517) with additional fields, all bytes are base64url encoded
type JwkProperties struct {
	Alg *JwkAlg `json:"alg,omitempty"`

	// E RSA exponent
	E Base64RawURLEncodableBytes `json:"e,omitempty"`

	// KeySize RSA key size
	KeySize *int32 `json:"key_size,omitempty"`

	// Kid Key ID
	KeyID *string `json:"kid,omitempty"`
	Kty   JwtKty  `json:"kty"`

	// N RSA modulus
	N Base64RawURLEncodableBytes `json:"n,omitempty"`

	// X EC x coordinate
	X Base64RawURLEncodableBytes `json:"x,omitempty"`

	// X5c X.509 certificate chain
	CertificateChain []Base64RawURLEncodableBytes `json:"x5c,omitempty"`

	// X5t X.509 certificate SHA-1 thumbprint
	CertificateThumbprint Base64RawURLEncodableBytes `json:"x5t,omitempty"`

	// X5tS256 X.509 certificate SHA-256 thumbprint
	CertificateThumbprintSHA256 Base64RawURLEncodableBytes `json:"x5t#S256,omitempty"`

	// X5u X.509 certificate URL
	CertificateURL *string `json:"x5u,omitempty"`

	// Y EC y coordinate
	Y Base64RawURLEncodableBytes `json:"y,omitempty"`
}

// JwtKty defines model for JwtKty.
type JwtKty string

// NamespaceIdentifier defines model for NamespaceIdentifier.
type NamespaceIdentifier = identifierWithKind[NamespaceKind]

// NamespaceKind defines model for NamespaceKind.
type NamespaceKind string

// ResourceIdentifier defines model for ResourceIdentifier.
type ResourceIdentifier = identifierWithKind[ResourceKind]

// ResourceKind defines model for ResourceKind.
type ResourceKind string

// ResourceLocator defines model for ResourceLocator.
type ResourceLocator = locator[NamespaceKind, ResourceKind]

// ResourceRef defines model for ResourceRef.
type ResourceRef struct {
	// Deleted Time when the deleted was deleted
	Deleted  *time.Time             `json:"deleted,omitempty"`
	Id       Identifier             `json:"id"`
	Locator  ResourceLocator        `json:"locator"`
	Metadata map[string]interface{} `json:"metadata,omitempty"`

	// Updated Time when the resoruce was last updated
	Updated   *time.Time `json:"updated,omitempty"`
	UpdatedBy *string    `json:"updatedBy,omitempty"`
}

// SubjectAlternativeNames defines model for SubjectAlternativeNames.
type SubjectAlternativeNames struct {
	DNSNames    []string `json:"dnsNames,omitempty"`
	Emails      []string `json:"emails,omitempty"`
	IPAddresses []net.IP `json:"ipAddresses,omitempty"`
}

// TemplatedCertificateTag defines model for TemplatedCertificateTag.
type TemplatedCertificateTag string

// WellknownCertificateTemplateName defines model for WellknownCertificateTemplateName.
type WellknownCertificateTemplateName string
