// <auto-generated/>
using Microsoft.Kiota.Abstractions;
using SmallKms.Client.V1.Certificates.Enroll;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace SmallKms.Client.V1.Certificates {
    /// <summary>
    /// Builds and executes requests for operations under \v1\certificates
    /// </summary>
    public class CertificatesRequestBuilder : BaseRequestBuilder {
        /// <summary>The enroll property</summary>
        public EnrollRequestBuilder Enroll { get =>
            new EnrollRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new CertificatesRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CertificatesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/certificates", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new CertificatesRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CertificatesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/certificates", rawUrl) {
        }
    }
}
