// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SmallKms.Client.Models {
    public enum CertificateIdentifierType {
        [EnumMember(Value = "certId")]
        CertId,
        [EnumMember(Value = "policyId")]
        PolicyId,
    }
}
