// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace SmallKms.Client.Models {
    public class CertificateRequestPolicyParameters : CertificateIssuerParameters, IParsable {
        /// <summary>The keyProperties property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public SmallKms.Client.Models.KeyProperties? KeyProperties { get; set; }
#nullable restore
#else
        public SmallKms.Client.Models.KeyProperties KeyProperties { get; set; }
#endif
        /// <summary>The lifetimeTrigger property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public CertificateLifetimeTrigger? LifetimeTrigger { get; set; }
#nullable restore
#else
        public CertificateLifetimeTrigger LifetimeTrigger { get; set; }
#endif
        /// <summary>The subject property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public CertificateSubject? Subject { get; set; }
#nullable restore
#else
        public CertificateSubject Subject { get; set; }
#endif
        /// <summary>The subjectAlternativeNames property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public CertificateSubjectAlternativeNames? SubjectAlternativeNames { get; set; }
#nullable restore
#else
        public CertificateSubjectAlternativeNames SubjectAlternativeNames { get; set; }
#endif
        /// <summary>The usage property</summary>
        public CertificateUsage? Usage { get; set; }
        /// <summary>The validity_months property</summary>
        public int? ValidityMonths { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new CertificateRequestPolicyParameters CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new CertificateRequestPolicyParameters();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public new IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers()) {
                {"keyProperties", n => { KeyProperties = n.GetObjectValue<SmallKms.Client.Models.KeyProperties>(SmallKms.Client.Models.KeyProperties.CreateFromDiscriminatorValue); } },
                {"lifetimeTrigger", n => { LifetimeTrigger = n.GetObjectValue<CertificateLifetimeTrigger>(CertificateLifetimeTrigger.CreateFromDiscriminatorValue); } },
                {"subject", n => { Subject = n.GetObjectValue<CertificateSubject>(CertificateSubject.CreateFromDiscriminatorValue); } },
                {"subjectAlternativeNames", n => { SubjectAlternativeNames = n.GetObjectValue<CertificateSubjectAlternativeNames>(CertificateSubjectAlternativeNames.CreateFromDiscriminatorValue); } },
                {"usage", n => { Usage = n.GetEnumValue<CertificateUsage>(); } },
                {"validity_months", n => { ValidityMonths = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public new void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteObjectValue<SmallKms.Client.Models.KeyProperties>("keyProperties", KeyProperties);
            writer.WriteObjectValue<CertificateLifetimeTrigger>("lifetimeTrigger", LifetimeTrigger);
            writer.WriteObjectValue<CertificateSubject>("subject", Subject);
            writer.WriteObjectValue<CertificateSubjectAlternativeNames>("subjectAlternativeNames", SubjectAlternativeNames);
            writer.WriteEnumValue<CertificateUsage>("usage", Usage);
            writer.WriteIntValue("validity_months", ValidityMonths);
        }
    }
}
