// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SmallKms.Client.Models {
    public enum CertificateUsage {
        [EnumMember(Value = "root-ca")]
        RootCa,
        [EnumMember(Value = "intermediate-ca")]
        IntermediateCa,
        [EnumMember(Value = "server-and-client")]
        ServerAndClient,
        [EnumMember(Value = "server-only")]
        ServerOnly,
        [EnumMember(Value = "client-only")]
        ClientOnly,
        [EnumMember(Value = "aad-client-credential")]
        AadClientCredential,
    }
}
