// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SmallKms.Client.Models {
    public enum NamespaceTypeShortName {
        [EnumMember(Value = "any")]
        Any,
        [EnumMember(Value = "root-ca")]
        RootCa,
        [EnumMember(Value = "intermediate-ca")]
        IntermediateCa,
        [EnumMember(Value = "service-principal")]
        ServicePrincipal,
        [EnumMember(Value = "group")]
        Group,
        [EnumMember(Value = "device")]
        Device,
        [EnumMember(Value = "user")]
        User,
        [EnumMember(Value = "application")]
        Application,
    }
}
