// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace SmallKms.Client.Models {
    public class ResourceRef : IAdditionalDataHolder, IParsable {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Time when the policy was deleted</summary>
        public DateTimeOffset? Deleted { get; set; }
        /// <summary>The id property</summary>
        public Guid? Id { get; set; }
        /// <summary>Unique ID of the namespace</summary>
        public Guid? NamespaceId { get; set; }
        /// <summary>Time when the policy was last updated</summary>
        public DateTimeOffset? Updated { get; set; }
        /// <summary>Unique ID of the user who created the policy</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedBy { get; set; }
#nullable restore
#else
        public string UpdatedBy { get; set; }
#endif
        /// <summary>
        /// Instantiates a new ResourceRef and sets the default values.
        /// </summary>
        public ResourceRef() {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static ResourceRef CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new ResourceRef();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"deleted", n => { Deleted = n.GetDateTimeOffsetValue(); } },
                {"id", n => { Id = n.GetGuidValue(); } },
                {"namespaceId", n => { NamespaceId = n.GetGuidValue(); } },
                {"updated", n => { Updated = n.GetDateTimeOffsetValue(); } },
                {"updatedBy", n => { UpdatedBy = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("deleted", Deleted);
            writer.WriteGuidValue("id", Id);
            writer.WriteGuidValue("namespaceId", NamespaceId);
            writer.WriteDateTimeOffsetValue("updated", Updated);
            writer.WriteStringValue("updatedBy", UpdatedBy);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
