// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package models

import (
	"time"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for CertificateUsage.
const (
	CertFeatCA         CertificateUsage = "ca"
	CertFeatCARoot     CertificateUsage = "ca-root"
	CertFeatClientAuth CertificateUsage = "clientAuth"
	CertFeatServerAuth CertificateUsage = "serverAuth"
)

// Defines values for JwkAlg.
const (
	AlgES256 JwkAlg = "ES256"
	AlgES384 JwkAlg = "ES384"
	AlgRS256 JwkAlg = "RS256"
	AlgRS384 JwkAlg = "RS384"
	AlgRS512 JwkAlg = "RS512"
)

// Defines values for KeyOp.
const (
	KeyOpDecrypt   KeyOp = "decrypt"
	KeyOpEncrypt   KeyOp = "encrypt"
	KeyOpSign      KeyOp = "sign"
	KeyOpUnwrapKey KeyOp = "unwrapKey"
	KeyOpVerify    KeyOp = "verify"
	KeyOpWrapKey   KeyOp = "wrapKey"
)

// Defines values for JwtCrv.
const (
	CurveNameP256 JwtCrv = "P-256"
	CurveNameP384 JwtCrv = "P-384"
)

// Defines values for JwtKty.
const (
	KeyTypeEC  JwtKty = "EC"
	KeyTypeRSA JwtKty = "RSA"
)

// Defines values for ProfileType.
const (
	ProfileTypeApplication      ProfileType = "application"
	ProfileTypeDevice           ProfileType = "device"
	ProfileTypeGroup            ProfileType = "group"
	ProfileTypeIntermediateCA   ProfileType = "intermediate-ca"
	ProfileTypeRootCA           ProfileType = "root-ca"
	ProfileTypeServicePrincipal ProfileType = "service-principal"
	ProfileTypeUser             ProfileType = "user"
)

// Defines values for ResourceType.
const (
	ResourceTypeCertificate                  ResourceType = "certificate"
	ResourceTypeCertificateEnrollmentReceipt ResourceType = "certificate-enrollment-receipt"
	ResourceTypeCertificateTemplate          ResourceType = "certificate-template"
	ResourceTypeProfile                      ResourceType = "profile"
)

// CertificateUsage defines model for CertificateUsage.
type CertificateUsage string

// Identifier Identifier of the resource
type Identifier = string

// JwkAlg defines model for JwkAlg.
type JwkAlg string

// KeyOp defines model for JwkKeyOperation.
type KeyOp string

// JwkProperties Property bag of JSON Web Key (RFC 7517) with additional fields, all bytes are base64url encoded
type JwkProperties struct {
	Alg *JwkAlg `json:"alg,omitempty"`
	Crv *JwtCrv `json:"crv,omitempty"`

	// E RSA exponent
	E     *string `json:"e,omitempty"`
	KeyOp *KeyOp  `json:"key_ops,omitempty"`

	// KeySize RSA key size
	KeySize *int `json:"key_size,omitempty"`

	// Kid Key ID
	KeyID *string `json:"kid,omitempty"`
	Kty   JwtKty  `json:"kty"`

	// N RSA modulus
	N *string `json:"n,omitempty"`

	// X EC x coordinate
	X *string `json:"x,omitempty"`

	// X5c X.509 certificate chain
	CertificateChain []string `json:"x5c,omitempty"`

	// X5t X.509 certificate SHA-1 thumbprint
	CertificateThumbprint *string `json:"x5t,omitempty"`

	// X5tS256 X.509 certificate SHA-256 thumbprint
	CertificateThumbprintSHA256 *string `json:"x5t#S256,omitempty"`

	// X5u X.509 certificate URL
	CertificateURL *string `json:"x5u,omitempty"`

	// Y EC y coordinate
	Y *string `json:"y,omitempty"`
}

// JwtCrv defines model for JwtCrv.
type JwtCrv string

// JwtKty defines model for JwtKty.
type JwtKty string

// Profile defines model for Profile.
type Profile struct {
	Ref  ResourceRef `json:"ref"`
	Type ProfileType `json:"type"`
}

// ProfileType defines model for ProfileType.
type ProfileType string

// ResourceRef defines model for ResourceRef.
type ResourceRef struct {
	// Deleted Time when the deleted was deleted
	Deleted *time.Time `json:"deleted,omitempty"`

	// Identifier Identifier of the resource
	Identifier *Identifier        `json:"identifier,omitempty"`
	Metadata   *map[string]string `json:"metadata,omitempty"`
	Type       ResourceType       `json:"type"`

	// Updated Time when the resoruce was last updated
	Updated *time.Time `json:"updated,omitempty"`
}

// ResourceType defines model for ResourceType.
type ResourceType string

// IdentifierParameter Identifier of the resource
type IdentifierParameter = Identifier

// ProfileTypeParameter defines model for ProfileTypeParameter.
type ProfileTypeParameter = ProfileType

// RefListResponse defines model for RefListResponse.
type RefListResponse = []ResourceRef
