// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package models

import (
	"time"
)

// ApplicationByAppId defines model for ApplicationByAppId.
type ApplicationByAppId = applicationByAppIdComposed

// ApplicationByAppIdFields defines model for ApplicationByAppIdFields.
type ApplicationByAppIdFields struct {
	ApplicationId      string `json:"applicationId"`
	ServicePrincipalId string `json:"servicePrincipalId"`
}

// Ref defines model for Ref.
type Ref struct {
	Deleted     *time.Time `json:"deleted,omitempty"`
	DisplayName string     `json:"displayName,omitempty"`
	ID          string     `json:"id"`
	Updated     time.Time  `json:"updated"`
	UpdatedBy   string     `json:"updatedBy"`
}

// RefsResponse defines model for RefsResponse.
type RefsResponse = Ref
