// Package agentpush provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package agentpush

import (
	"github.com/docker/docker/api/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// DockerInfo defines model for DockerInfo.
type DockerInfo = types.Info

// DelegatedAuthorizationHeaderParameter defines model for DelegatedAuthorizationHeaderParameter.
type DelegatedAuthorizationHeaderParameter = string

// GetAgentDiagnosticsParams defines parameters for GetAgentDiagnostics.
type GetAgentDiagnosticsParams struct {
	XCryptocatProxyAuthorization *DelegatedAuthorizationHeaderParameter `json:"X-Cryptocat-Proxy-Authorization,omitempty"`
}

// GetAgentDockerInfoParams defines parameters for GetAgentDockerInfo.
type GetAgentDockerInfoParams struct {
	XCryptocatProxyAuthorization *DelegatedAuthorizationHeaderParameter `json:"X-Cryptocat-Proxy-Authorization,omitempty"`
}
