// Package agentpush provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package agentpush

import (
	"github.com/docker/docker/api/types"
	"github.com/docker/docker/api/types/container"
	externalRef1 "github.com/stephenzsy/small-kms/backend/managedapp"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// DockerContainer defines model for DockerContainer.
type DockerContainer = types.Container

// DockerContainerJSON defines model for DockerContainerJSON.
type DockerContainerJSON = types.ContainerJSON

// DockerImageSummary defines model for DockerImageSummary.
type DockerImageSummary = types.ImageSummary

// DockerInfo defines model for DockerInfo.
type DockerInfo = types.Info

// DockerNetworkResource defines model for DockerNetworkResource.
type DockerNetworkResource = types.NetworkResource

// LaunchAgentRequest defines model for LaunchAgentRequest.
type LaunchAgentRequest struct {
	ContainerName                 string                     `json:"containerName"`
	Env                           []string                   `json:"env,omitempty"`
	ExposedPortSpecs              []string                   `json:"exposedPortSpecs"`
	HostBinds                     []string                   `json:"hostBinds"`
	ImageTag                      string                     `json:"imageTag"`
	ListenerAddress               string                     `json:"listenerAddress"`
	Mode                          externalRef1.AgentMode     `json:"mode"`
	MsEntraIdClientCertSecretName string                     `json:"msEntraIdClientCertSecretName,omitempty"`
	NetworkName                   string                     `json:"networkName,omitempty"`
	PushEndpoint                  string                     `json:"pushEndpoint"`
	Secrets                       []externalRef1.SecretMount `json:"secrets"`
}

// PullImageRequest defines model for PullImageRequest.
type PullImageRequest struct {
	ImageRepo        string `json:"imageRepo,omitempty"`
	ImageTag         string `json:"imageTag"`
	IncludeLatestTag *bool  `json:"includeLatestTag,omitempty"`
}

// DelegatedAuthorizationHeaderParameter defines model for DelegatedAuthorizationHeaderParameter.
type DelegatedAuthorizationHeaderParameter = string

// DockerContianerCreateResponse defines model for DockerContianerCreateResponse.
type DockerContianerCreateResponse = container.CreateResponse

// PushAgentConfigRadiusParams defines parameters for PushAgentConfigRadius.
type PushAgentConfigRadiusParams struct {
	XCryptocatProxyAuthorization *DelegatedAuthorizationHeaderParameter `json:"X-Cryptocat-Proxy-Authorization,omitempty"`
}

// GetAgentDiagnosticsParams defines parameters for GetAgentDiagnostics.
type GetAgentDiagnosticsParams struct {
	XCryptocatProxyAuthorization *DelegatedAuthorizationHeaderParameter `json:"X-Cryptocat-Proxy-Authorization,omitempty"`
}

// AgentDockerContainerListParams defines parameters for AgentDockerContainerList.
type AgentDockerContainerListParams struct {
	XCryptocatProxyAuthorization *DelegatedAuthorizationHeaderParameter `json:"X-Cryptocat-Proxy-Authorization,omitempty"`
}

// AgentDockerContainerRemoveParams defines parameters for AgentDockerContainerRemove.
type AgentDockerContainerRemoveParams struct {
	XCryptocatProxyAuthorization *DelegatedAuthorizationHeaderParameter `json:"X-Cryptocat-Proxy-Authorization,omitempty"`
}

// AgentDockerContainerInspectParams defines parameters for AgentDockerContainerInspect.
type AgentDockerContainerInspectParams struct {
	XCryptocatProxyAuthorization *DelegatedAuthorizationHeaderParameter `json:"X-Cryptocat-Proxy-Authorization,omitempty"`
}

// AgentDockerContainerStopParams defines parameters for AgentDockerContainerStop.
type AgentDockerContainerStopParams struct {
	XCryptocatProxyAuthorization *DelegatedAuthorizationHeaderParameter `json:"X-Cryptocat-Proxy-Authorization,omitempty"`
}

// AgentDockerImageListParams defines parameters for AgentDockerImageList.
type AgentDockerImageListParams struct {
	XCryptocatProxyAuthorization *DelegatedAuthorizationHeaderParameter `json:"X-Cryptocat-Proxy-Authorization,omitempty"`
}

// AgentDockerInfoParams defines parameters for AgentDockerInfo.
type AgentDockerInfoParams struct {
	XCryptocatProxyAuthorization *DelegatedAuthorizationHeaderParameter `json:"X-Cryptocat-Proxy-Authorization,omitempty"`
}

// AgentDockerNetworkListParams defines parameters for AgentDockerNetworkList.
type AgentDockerNetworkListParams struct {
	XCryptocatProxyAuthorization *DelegatedAuthorizationHeaderParameter `json:"X-Cryptocat-Proxy-Authorization,omitempty"`
}

// AgentLaunchAgentParams defines parameters for AgentLaunchAgent.
type AgentLaunchAgentParams struct {
	XCryptocatProxyAuthorization *DelegatedAuthorizationHeaderParameter `json:"X-Cryptocat-Proxy-Authorization,omitempty"`
}

// AgentPullImageParams defines parameters for AgentPullImage.
type AgentPullImageParams struct {
	XCryptocatProxyAuthorization *DelegatedAuthorizationHeaderParameter `json:"X-Cryptocat-Proxy-Authorization,omitempty"`
}

// AgentLaunchAgentJSONRequestBody defines body for AgentLaunchAgent for application/json ContentType.
type AgentLaunchAgentJSONRequestBody = LaunchAgentRequest

// AgentPullImageJSONRequestBody defines body for AgentPullImage for application/json ContentType.
type AgentPullImageJSONRequestBody = PullImageRequest
