/* tslint:disable */
/* eslint-disable */
/**
 * Small KMS Admin API Shared
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CertificateTemplateRef
 */
export interface CertificateTemplateRef {
    /**
     * Identifier of the resource
     * @type {string}
     * @memberof CertificateTemplateRef
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CertificateTemplateRef
     */
    locator: string;
    /**
     * Time when the resoruce was last updated
     * @type {Date}
     * @memberof CertificateTemplateRef
     */
    updated?: Date;
    /**
     * 
     * @type {string}
     * @memberof CertificateTemplateRef
     */
    updatedBy?: string;
    /**
     * Time when the deleted was deleted
     * @type {Date}
     * @memberof CertificateTemplateRef
     */
    deleted?: Date;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof CertificateTemplateRef
     */
    metadata?: { [key: string]: string; };
    /**
     * Common name
     * @type {string}
     * @memberof CertificateTemplateRef
     */
    subjectCommonName: string;
}

/**
 * Check if a given object implements the CertificateTemplateRef interface.
 */
export function instanceOfCertificateTemplateRef(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "locator" in value;
    isInstance = isInstance && "subjectCommonName" in value;

    return isInstance;
}

export function CertificateTemplateRefFromJSON(json: any): CertificateTemplateRef {
    return CertificateTemplateRefFromJSONTyped(json, false);
}

export function CertificateTemplateRefFromJSONTyped(json: any, ignoreDiscriminator: boolean): CertificateTemplateRef {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'locator': json['locator'],
        'updated': !exists(json, 'updated') ? undefined : (new Date(json['updated'])),
        'updatedBy': !exists(json, 'updatedBy') ? undefined : json['updatedBy'],
        'deleted': !exists(json, 'deleted') ? undefined : (new Date(json['deleted'])),
        'metadata': !exists(json, 'metadata') ? undefined : json['metadata'],
        'subjectCommonName': json['subjectCommonName'],
    };
}

export function CertificateTemplateRefToJSON(value?: CertificateTemplateRef | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'locator': value.locator,
        'updated': value.updated === undefined ? undefined : (value.updated.toISOString()),
        'updatedBy': value.updatedBy,
        'deleted': value.deleted === undefined ? undefined : (value.deleted.toISOString()),
        'metadata': value.metadata,
        'subjectCommonName': value.subjectCommonName,
    };
}

