/* tslint:disable */
/* eslint-disable */
/**
 * Small KMS Admin API Shared
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { NamespaceKind } from './NamespaceKind';
import {
    NamespaceKindFromJSON,
    NamespaceKindFromJSONTyped,
    NamespaceKindToJSON,
} from './NamespaceKind';

/**
 * 
 * @export
 * @interface CertificateIssuer
 */
export interface CertificateIssuer {
    /**
     * 
     * @type {NamespaceKind}
     * @memberof CertificateIssuer
     */
    profileType: NamespaceKind;
    /**
     * Identifier of the resource
     * @type {string}
     * @memberof CertificateIssuer
     */
    profileId: string;
    /**
     * Identifier of the resource
     * @type {string}
     * @memberof CertificateIssuer
     */
    templateId?: string;
    /**
     * 
     * @type {string}
     * @memberof CertificateIssuer
     */
    certificateId?: string;
}

/**
 * Check if a given object implements the CertificateIssuer interface.
 */
export function instanceOfCertificateIssuer(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "profileType" in value;
    isInstance = isInstance && "profileId" in value;

    return isInstance;
}

export function CertificateIssuerFromJSON(json: any): CertificateIssuer {
    return CertificateIssuerFromJSONTyped(json, false);
}

export function CertificateIssuerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CertificateIssuer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'profileType': NamespaceKindFromJSON(json['profileType']),
        'profileId': json['profileId'],
        'templateId': !exists(json, 'templateId') ? undefined : json['templateId'],
        'certificateId': !exists(json, 'certificateId') ? undefined : json['certificateId'],
    };
}

export function CertificateIssuerToJSON(value?: CertificateIssuer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'profileType': NamespaceKindToJSON(value.profileType),
        'profileId': value.profileId,
        'templateId': value.templateId,
        'certificateId': value.certificateId,
    };
}

