import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppMsalProvider } from "./_client/AppMsalProvider";
import "./globals.css";
import classNames from "classnames";
import AppLayout from "./_client/AppLayout";
import { GraphClientProvider } from "./_client/MsGraphClientProvider";
import { AdminApiProvider } from "@/client/useClient";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full bg-gray-100">
      <body className={classNames(inter.className, "h-full")}>
        <div className="min-h-full">
          <AppMsalProvider>
            <AdminApiProvider>
              <GraphClientProvider>
                <AppLayout>{children}</AppLayout>
              </GraphClientProvider>
            </AdminApiProvider>
          </AppMsalProvider>
        </div>
      </body>
    </html>
  );
}
