// <auto-generated/>
using Microsoft.Kiota.Abstractions;
using SmallKms.Client.V2.Group.Item;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace SmallKms.Client.V2.Group {
    /// <summary>
    /// Builds and executes requests for operations under \v2\group
    /// </summary>
    public class GroupRequestBuilder : BaseRequestBuilder {
        /// <summary>Gets an item from the SmallKms.Client.v2.group.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        public WithNamespaceItemRequestBuilder this[string position] { get {
            var urlTplParams = new Dictionary<string, object>(PathParameters);
            urlTplParams.Add("namespaceId", position);
            return new WithNamespaceItemRequestBuilder(urlTplParams, RequestAdapter);
        } }
        /// <summary>
        /// Instantiates a new GroupRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GroupRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/group", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new GroupRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GroupRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/group", rawUrl) {
        }
    }
}
