openapi: 3.0.3
info:
  title: Intune SCEP Validation
  version: 0.1.0
servers:
  - url: https://api.manage.microsoft.com/
    description: Default intunes resource url
paths:
  /ScepActions/validateRequest:
    post:
      tags:
        - intune
      summary: Validate request
      operationId: ValidateRequest
      requestBody:
        required: true
        content:
          application/json:
            schema:
              title: IntuneScepValidateRequestBody
              type: object
              properties:
                request:
                  $ref: "#/components/schemas/IntuneScepValidateRequest"
              required:
                - request
      responses:
        "200":
          description: SCEP Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/IntuneScepResponse"
security:
  - BearerAuth: []
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    IntuneScepValidateRequest:
      type: object
      properties:
        transactionId:
          type: string
        certificateRequest:
          type: string
          format: byte
        callerInfo:
          type: string
      required:
        - transactionId
        - certificateRequest
    IntuneScepResponse:
      type: object
      properties:
        code:
          type: string
        errorDescription:
          type: string
          enum:
            - Unknown
            - Success
