openapi: 3.0.3
info:
  title: Cryptocat API
  version: 0.1.3
servers:
  - url: https://example.com
    description: Local server
security:
  - BearerAuth: []
paths:
  /v2/agents:
    get:
      tags:
        - admin
      summary: List agents
      operationId: ListAgents
      responses:
        200:
          $ref: "models-shared.yaml#/components/responses/RefsResponse"
    post:
      tags:
        - admin
      summary: Create agent
      operationId: CreateAgent
      requestBody:
        content:
          application/json:
            schema:
              $ref: "models-agent.yaml#/components/schemas/CreateAgentRequest"
      responses:
        201:
          $ref: "models-agent.yaml#/components/responses/AgentResposne"
        200:
          $ref: "models-agent.yaml#/components/responses/AgentResposne"
  /v2/system-app/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
    get:
      tags:
        - admin
      operationId: GetSystemApp
      summary: Get system app
      responses:
        200:
          $ref: "models-shared.yaml#/components/responses/ApplicationByAppIdResponse"
    post:
      tags:
        - admin
      operationId: SyncSystemApp
      summary: Sync managed app
      responses:
        200:
          $ref: "models-shared.yaml#/components/responses/ApplicationByAppIdResponse"
        201:
          $ref: "models-shared.yaml#/components/responses/ApplicationByAppIdResponse"
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
