openapi: 3.0.3
info:
  title: Cryptocat API
  version: 0.1.3
servers:
  - url: https://example.com
    description: Local server
security:
  - BearerAuth: []
paths:
  /v2/agents:
    post:
      tags:
        - admin
      summary: Create agent
      operationId: CreateAgent
      requestBody:
        content:
          application/json:
            schema:
              $ref: "models-agent.yaml#/components/schemas/CreateAgentRequest"
      responses:
        201:
          $ref: "models-agent.yaml#/components/responses/AgentResposne"
        200:
          $ref: "models-agent.yaml#/components/responses/AgentResposne"
        400:
          $ref: "#/components/responses/ErrorResponse"
  /v2/agents/{id}:
    parameters:
      - $ref: "#/components/parameters/IdParameter"
    get:
      tags:
        - admin
      operationId: GetAgent
      summary: Get agent
      responses:
        200:
          $ref: "models-agent.yaml#/components/responses/AgentResposne"
        404:
          $ref: "#/components/responses/ErrorResponse"
  /v2/profiles/{namespaceProvider}:
    parameters:
      - $ref: "#/components/parameters/NamespaceProviderParameter"
    get:
      tags:
        - admin
      operationId: ListProfiles
      summary: list profiles
      responses:
        200:
          $ref: "models-shared.yaml#/components/responses/RefsResponse"
        404:
          $ref: "#/components/responses/ErrorResponse"
  /v2/profiles/{namespaceProvider}/{namespaceId}:
    parameters:
      - $ref: "#/components/parameters/NamespaceProviderParameter"
      - $ref: "#/components/parameters/NamespaceIdParameter"
    get:
      tags:
        - admin
      operationId: GetProfile
      summary: Get profile
      responses:
        200:
          $ref: "models-shared.yaml#/components/responses/ProfileResponse"
        404:
          $ref: "#/components/responses/ErrorResponse"
    post:
      tags:
        - admin
      operationId: SyncProfile
      summary: Sync profile
      responses:
        200:
          $ref: "models-shared.yaml#/components/responses/ProfileResponse"
        404:
          $ref: "#/components/responses/ErrorResponse"
  /v2/system-apps/{id}:
    parameters:
      - $ref: "#/components/parameters/IdParameter"
    get:
      tags:
        - admin
      operationId: GetSystemApp
      summary: Get system app
      responses:
        200:
          $ref: "models-shared.yaml#/components/responses/ProfileResponse"
        404:
          $ref: "#/components/responses/ErrorResponse"
    post:
      tags:
        - admin
      operationId: SyncSystemApp
      summary: Sync managed app
      responses:
        200:
          $ref: "models-shared.yaml#/components/responses/ProfileResponse"
        201:
          $ref: "models-shared.yaml#/components/responses/ProfileResponse"
        400:
          $ref: "#/components/responses/ErrorResponse"
  /v2/{namespaceProvider}/{namespaceId}/certificate-policies:
    parameters:
      - $ref: "#/components/parameters/NamespaceProviderParameter"
      - $ref: "#/components/parameters/NamespaceIdParameter"
    get:
      tags:
        - admin
      summary: List certificate policies
      operationId: ListCertificatePolicies
      responses:
        200:
          $ref: "models-shared.yaml#/components/responses/RefsResponse"
  /v2/{namespaceProvider}/{namespaceId}/certificate-policies/{id}:
    parameters:
      - $ref: "#/components/parameters/NamespaceProviderParameter"
      - $ref: "#/components/parameters/NamespaceIdParameter"
      - $ref: "#/components/parameters/IdParameter"
    get:
      tags:
        - admin
        - agentclient
      operationId: GetCertificatePolicy
      summary: Get certificate policy
      responses:
        200:
          $ref: "models-cert.yaml#/components/responses/CertificatePolicyResponse"
        404:
          $ref: "#/components/responses/ErrorResponse"
    put:
      tags:
        - admin
      operationId: PutCertificatePolicy
      summary: put certificate policy
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "models-cert.yaml#/components/schemas/CreateCertificatePolicyRequest"
      responses:
        200:
          $ref: "models-cert.yaml#/components/responses/CertificatePolicyResponse"
        201:
          $ref: "models-cert.yaml#/components/responses/CertificatePolicyResponse"
        400:
          $ref: "#/components/responses/ErrorResponse"
  /v2/{namespaceProvider}/{namespaceId}/certificate-policies/{id}/issuer:
    parameters:
      - $ref: "#/components/parameters/NamespaceProviderParameter"
      - $ref: "#/components/parameters/NamespaceIdParameter"
      - $ref: "#/components/parameters/IdParameter"
    get:
      tags:
        - admin
      operationId: GetCertificatePolicyIssuer
      summary: Get certificate policy issuer
      responses:
        200:
          $ref: "models-shared.yaml#/components/responses/LinkRefResponse"
        404:
          $ref: "#/components/responses/ErrorResponse"
    put:
      tags:
        - admin
      operationId: PutCertificatePolicyIssuer
      summary: put certificate policy issuer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "models-shared.yaml#/components/schemas/LinkRefFields"
      responses:
        200:
          $ref: "models-shared.yaml#/components/responses/LinkRefResponse"
        201:
          $ref: "models-shared.yaml#/components/responses/LinkRefResponse"
        400:
          $ref: "#/components/responses/ErrorResponse"
  /v2/{namespaceProvider}/{namespaceId}/certificate-policies/{id}/generate:
    parameters:
      - $ref: "#/components/parameters/NamespaceProviderParameter"
      - $ref: "#/components/parameters/NamespaceIdParameter"
      - $ref: "#/components/parameters/IdParameter"
    post:
      tags:
        - admin
      operationId: GenerateCertificate
      summary: put certificate policy
      responses:
        201:
          $ref: "models-cert.yaml#/components/responses/CertificateResponse"
        400:
          $ref: "#/components/responses/ErrorResponse"
        403:
          $ref: "#/components/responses/ErrorResponse"
  /v2/{namespaceProvider}/{namespaceId}/certificate-policies/{id}/enroll:
    parameters:
      - $ref: "#/components/parameters/NamespaceProviderParameter"
      - $ref: "#/components/parameters/NamespaceIdParameter"
      - $ref: "#/components/parameters/IdParameter"
    post:
      tags:
        - admin
        - agentclient
      parameters:
        - in: query
          name: onBehalfOfApplication
          description: Enroll on behalf of application, must have a bearer token with "azp" cliam
          required: false
          schema:
            type: boolean
      operationId: EnrollCertificate
      summary: put certificate policy
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "models-cert.yaml#/components/schemas/EnrollCertificateRequest"
      responses:
        201:
          $ref: "models-cert.yaml#/components/responses/CertificateResponse"
        400:
          $ref: "#/components/responses/ErrorResponse"
        403:
          $ref: "#/components/responses/ErrorResponse"
  /v2/{namespaceProvider}/{namespaceId}/certificates:
    parameters:
      - $ref: "#/components/parameters/NamespaceProviderParameter"
      - $ref: "#/components/parameters/NamespaceIdParameter"
    get:
      tags:
        - admin
      operationId: ListCertificates
      summary: List certificates
      parameters:
        - name: policyId
          in: query
          description: Policy ID
          required: false
          schema:
            type: string
      responses:
        200:
          $ref: "models-cert.yaml#/components/responses/CertificateRefsResponse"
  /v2/{namespaceProvider}/{namespaceId}/certificates/{id}:
    parameters:
      - $ref: "#/components/parameters/NamespaceProviderParameter"
      - $ref: "#/components/parameters/NamespaceIdParameter"
      - $ref: "#/components/parameters/IdParameter"
    get:
      tags:
        - admin
      operationId: GetCertificate
      summary: Get certificate
      parameters:
        - in: query
          name: includeJwk
          description: Include JWK
          required: false
          schema:
            type: boolean
      responses:
        200:
          $ref: "models-cert.yaml#/components/responses/CertificateResponse"
        404:
          $ref: "#/components/responses/ErrorResponse"
    delete:
      tags:
        - admin
      operationId: DeleteCertificate
      summary: Delete certificate
      responses:
        200:
          $ref: "models-cert.yaml#/components/responses/CertificateResponse"
        204:
          $ref: "#/components/responses/NoContentResponse"
        400:
          $ref: "#/components/responses/ErrorResponse"
  /v2/{namespaceProvider}/{namespaceId}/certificates/{id}/ms-entra-key-credential:
    parameters:
      - $ref: "#/components/parameters/NamespaceProviderParameter"
      - $ref: "#/components/parameters/NamespaceIdParameter"
      - $ref: "#/components/parameters/IdParameter"
    post:
      parameters:
        - in: query
          name: onBehalfOfApplication
          description: add entra key on onBehalfOfApplication
          required: false
          schema:
            type: boolean
      tags:
        - admin
      operationId: AddMsEntraKeyCredential
      summary: Add certificate as MS Entra key credential
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "models-cert.yaml#/components/schemas/AddMsEntraKeyCredentialRequest"
      responses:
        204:
          $ref: "#/components/responses/NoContentResponse"
        404:
          $ref: "#/components/responses/ErrorResponse"
  /v2/{namespaceProvider}/{namespaceId}/key-policies:
    parameters:
      - $ref: "#/components/parameters/NamespaceProviderParameter"
      - $ref: "#/components/parameters/NamespaceIdParameter"
    get:
      tags:
        - admin
      operationId: ListKeyPolicies
      summary: List key policies
      responses:
        200:
          $ref: "models-shared.yaml#/components/responses/RefsResponse"
  /v2/{namespaceProvider}/{namespaceId}/key-policies/{id}:
    parameters:
      - $ref: "#/components/parameters/NamespaceProviderParameter"
      - $ref: "#/components/parameters/NamespaceIdParameter"
      - $ref: "#/components/parameters/IdParameter"
    get:
      tags:
        - admin
      operationId: GetKeyPolicy
      summary: Get key policy
      responses:
        200:
          $ref: "models-key.yaml#/components/responses/KeyPolicyResponse"
        404:
          $ref: "#/components/responses/ErrorResponse"
    put:
      tags:
        - admin
      operationId: PutKeyPolicy
      summary: put key policy
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "models-key.yaml#/components/schemas/CreateKeyPolicyRequest"
      responses:
        200:
          $ref: "models-key.yaml#/components/responses/KeyPolicyResponse"
        201:
          $ref: "models-key.yaml#/components/responses/KeyPolicyResponse"
        400:
          $ref: "#/components/responses/ErrorResponse"
  /v2/{namespaceProvider}/{namespaceId}/memberOf/{id}:
    parameters:
      - $ref: "#/components/parameters/NamespaceProviderParameter"
      - $ref: "#/components/parameters/NamespaceIdParameter"
      - $ref: "#/components/parameters/IdParameter"
    get:
      tags:
        - admin
      operationId: GetMemberOf
      summary: Get member group
      responses:
        200:
          $ref: "models-shared.yaml#/components/responses/LinkRefResponse"
        404:
          $ref: "#/components/responses/ErrorResponse"
    post:
      tags:
        - admin
      operationId: SyncMemberOf
      summary: Sync member group
      responses:
        200:
          $ref: "models-shared.yaml#/components/responses/LinkRefResponse"
        404:
          $ref: "#/components/responses/ErrorResponse"
  /v2/service-principal/{namespaceId}/agent-config:
    parameters:
      - $ref: "#/components/parameters/NamespaceIdParameter"
    get:
      tags:
        - admin
      operationId: GetAgentConfig
      summary: Get agent config
      responses:
        200:
          $ref: "models-agent.yaml#/components/responses/AgentConfigResponse"
        404:
          $ref: "#/components/responses/ErrorResponse"
    put:
      tags:
        - admin
      operationId: PutAgentConfig
      summary: Put agent config
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "models-agent.yaml#/components/schemas/AgentConfigFields"
      responses:
        200:
          $ref: "models-agent.yaml#/components/responses/AgentConfigResponse"
        201:
          $ref: "models-agent.yaml#/components/responses/AgentConfigResponse"
        400:
          $ref: "#/components/responses/ErrorResponse"
components:
  parameters:
    IdParameter:
      in: path
      name: id
      required: true
      schema:
        type: string
    NamespaceProviderParameter:
      in: path
      name: namespaceProvider
      required: true
      schema:
        $ref: "models-shared.yaml#/components/schemas/NamespaceProvider"
    NamespaceIdParameter:
      in: path
      name: namespaceId
      required: true
      schema:
        type: string
  schemas:
    ErrorResult:
      type: object
      properties:
        message:
          type: string
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    NoContentResponse:
      description: No content response
      content: {}
    ErrorResponse:
      description: Error response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResult"
