openapi: 3.0.3
info:
  title: Cryptocat Cert Models
  version: 0.1.3
paths: {}
components:
  schemas:
    CertificateRef:
      allOf:
        - $ref: "models-shared.yaml#/components/schemas/Ref"
        - $ref: "#/components/schemas/CertificateRefFields"
        - x-go-type: certificateRefComposed
    CertificateRefFields:
      type: object
      properties:
        thumbprint:
          description: Hex encoded certificate thumbprint
          type: string
          x-go-type-skip-optional-pointer: true
        status:
          $ref: "#/components/schemas/CertificateStatus"
        iat:
          $ref: "models-shared.yaml#/components/schemas/NumericDate"
          x-go-name: IssuedAt
        exp:
          $ref: "models-shared.yaml#/components/schemas/NumericDate"
          x-go-name: NotAfter
        policyIdentifier:
          type: string
          x-go-type-skip-optional-pointer: true
      required:
        - status
        - thumbprint
        - exp
        - policyIdentifier
    Certificate:
      allOf:
        - $ref: "#/components/schemas/CertificateRef"
        - $ref: "#/components/schemas/CertificateFields"
        - x-go-type: certificateComposed
    CertificateFields:
      type: object
      properties:
        identififier:
          type: string
        issuerIdentifier:
          type: string
        serialNumber:
          type: string
        nbf:
          $ref: "models-shared.yaml#/components/schemas/NumericDate"
          x-go-name: NotBefore
        jwk:
          $ref: "models-key.yaml#/components/schemas/JsonWebKey"
        subject:
          type: string
        subjectAlternativeNames:
          $ref: "#/components/schemas/SubjectAlternativeNames"
        flags:
          type: array
          items:
            $ref: "#/components/schemas/CertificateFlag"
          x-go-type-skip-optional-pointer: true
        cid:
          description: Key Vault certificate ID
          type: string
          x-go-type-skip-optional-pointer: true
          x-go-name: KeyVaultCertificateID
        sid:
          description: Key Vault Secret ID
          type: string
          x-go-type-skip-optional-pointer: true
          x-go-name: KeyVaultSecretID
        oneTimePkcs12Key:
          description: Base64 encoded PKCS12 key
          $ref: "models-key.yaml#/components/schemas/JsonWebKey"
        pendingAcme:
          $ref: "#/components/schemas/CertificatePendingAcme"
      required:
        - identififier
        - issuerIdentifier
        - serialNumber
        - nbf
        - subject
    CertificateExternalIssuer:
      allOf:
        - $ref: "models-shared.yaml#/components/schemas/Ref"
        - $ref: "#/components/schemas/CertificateExternalIssuerFields"
        - x-go-type: certificateExternalIssuerComposed
    CertificateExternalIssuerFields:
      type: object
      properties:
        acme:
          $ref: "#/components/schemas/CertificateExternalIssuerAcme"
    CertificateExternalIssuerAcme:
      properties:
        directoryUrl:
          type: string
          x-go-name: DirectoryURL
        accountKeyId:
          type: string
          x-go-name: AccountKeyID
        accountUrl:
          type: string
          x-go-name: AccountURL
        contacts:
          type: array
          items:
            type: string
        azureDnsZoneResourceId:
          type: string
          x-go-name: AzureDNSZoneResourceID
      required:
        - directoryUrl
        - accountKeyId
        - accountUrl
        - contacts
        - azureDnsZoneResourceId
    CertificatePendingAcme:
      properties:
        authorizations:
          type: array
          items:
            $ref: "#/components/schemas/CertificatePendingAcmeAuthorization"
          x-go-type-skip-optional-pointer: true
    CertificatePendingAcmeAuthorization:
      properties:
        url:
          type: string
          description: URL to the authorization
          x-go-name: URL
        status:
          type: string
        challenges:
          type: array
          items:
            $ref: "#/components/schemas/CertificatePendingAcmeChallenge"
          x-go-type-skip-optional-pointer: true
      required:
        - url
        - status
    CertificatePendingAcmeChallenge:
      properties:
        type:
          type: string
        url:
          type: string
          description: URL to the challenge
          x-go-name: URL
        dnsRecord:
          type: string
          x-go-name: DNSRecord
          x-go-type-skip-optional-pointer: true
      required:
        - type
        - url
    UpdatePendingCertificateRequest:
      properties:
        acmeAcceptChallengeUrl:
          type: string
          x-go-name: AcmeAcceptChallenge
          x-go-type-skip-optional-pointer: true
        acmeOrderCertificate:
          type: boolean
          x-go-name: AcmeOrderCertificate
    CertificatePolicy:
      allOf:
        - $ref: "models-shared.yaml#/components/schemas/Ref"
        - $ref: "#/components/schemas/CertificatePolicyFields"
        - x-go-type: certificatePolicyComposed
    CertificateStatus:
      type: string
      enum:
        - pending-authorization
        - pending-csr
        - pending-issue
        - issued
        - revoked
        - deactivated
        - unverified
      x-enum-varnames:
        - CertificateStatusPendingAuthorization
        - CertificateStatusPendingCSR
        - CertificateStatusIssued
        - CertificateStatusRevoked
        - CertificateStatusDeactivated
        - CertificateStatusUnverified
    CertificatePolicyFields:
      type: object
      properties:
        keySpec:
          $ref: "models-key.yaml#/components/schemas/JsonWebKeySpec"
        keyExportable:
          type: boolean
        allowGenerate:
          type: boolean
        allowEnroll:
          type: boolean
        expiryTime:
          type: string
        issuerPolicyIdentifier:
          description: Policy identififier of parent issuer
          type: string
          x-go-type-skip-optional-pointer: true
        subject:
          $ref: "#/components/schemas/CertificateSubject"
        subjectAlternativeNames:
          $ref: "#/components/schemas/SubjectAlternativeNames"
        flags:
          type: array
          items:
            $ref: "#/components/schemas/CertificateFlag"
          x-go-type-skip-optional-pointer: true
      required:
        - keySpec
        - keyExportable
        - allowGenerate
        - allowEnroll
        - expiryTime
        - issuerPolicyIdentifier
        - subject
    CertificatePolicyParameters:
      type: object
      properties:
        displayName:
          type: string
          x-go-type-skip-optional-pointer: true
        issuerPolicyIdentifier:
          type: string
          x-go-type-skip-optional-pointer: true
        keySpec:
          $ref: "models-key.yaml#/components/schemas/JsonWebKeySpec"
        keyExportable:
          type: boolean
        allowGenerate:
          type: boolean
        allowEnroll:
          type: boolean
        expiryTime:
          type: string
          x-go-type-skip-optional-pointer: true
        subject:
          $ref: "#/components/schemas/CertificateSubject"
        subjectAlternativeNames:
          $ref: "#/components/schemas/SubjectAlternativeNames"
        flags:
          type: array
          items:
            $ref: "#/components/schemas/CertificateFlag"
          x-go-type-skip-optional-pointer: true
      required:
        - subject
    CertificateSubject:
      type: object
      properties:
        cn:
          type: string
          x-go-name: CommonName
      required:
        - cn
    CertificateFlag:
      type: string
      enum:
        - serverAuth
        - clientAuth
      x-enum-varnames:
        - CertificateFlagServerAuth
        - CertificateFlagClientAuth
    SubjectAlternativeNames:
      type: object
      properties:
        dnsNames:
          type: array
          items:
            type: string
          x-go-type-skip-optional-pointer: true
          x-go-name: DNSNames
        ipAddresses:
          type: array
          items:
            type: string
            x-go-type: net.IP
          x-go-type-skip-optional-pointer: true
          x-go-name: IPAddresses
        emails:
          type: array
          items:
            type: string
          x-go-type-skip-optional-pointer: true
    EnrollCertificateRequest:
      type: object
      properties:
        publicKey:
          $ref: "models-key.yaml#/components/schemas/JsonWebKey"
        withOneTimePkcs12Key:
          type: boolean
      required:
        - publicKey
    ExchangePKCS12Request:
      type: object
      properties:
        payload:
          type: string
          description: JWE encrypted private key in JWK
        legacy:
          type: boolean
          description: Use legacy PKCS12 cipher
        passwordProtected:
          type: boolean
          description: Encrypt the PKCS12 file with a generated password
      required:
        - payload
        - passwordProtected
    ExchangePKCS12Result:
      type: object
      properties:
        payload:
          type: string
          description: JWE encrypted PKCS12 file, encrypted with the symmetric key from the request
        password:
          type: string
          description: Password used to encrypt the PKCS12 file
      required:
        - payload
        - password
  responses:
    CertificateResponse:
      description: Certificate response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Certificate"
    CertificatePolicyResponse:
      description: CertificatePolicy response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/CertificatePolicy"
    CertificateRefsResponse:
      description: List of CertificateRefs response
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/CertificateRef"
    CertificateExternalIssuerResponse:
      description: CertificateIssuer response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/CertificateExternalIssuer"
