openapi: 3.0.3
info:
  title: Cryptocat Agent Models
  version: 0.1.3
paths: {}
components:
  schemas:
    Agent:
      $ref: "models-shared.yaml#/components/schemas/Profile"
    CreateAgentRequest:
      type: object
      properties:
        appId:
          description: The Application ID (Client ID) of the agent
          type: string
          x-go-type-skip-optional-pointer: true
        displayName:
          description: The display name of the agent application
          type: string
          x-go-type-skip-optional-pointer: true
    AgentConfig:
      allOf:
        - $ref: "models-shared.yaml#/components/schemas/Ref"
        - $ref: "#/components/schemas/AgentConfigFields"
        - x-go-type: agentConfigComposed
    AgentConfigFields:
      type: object
      properties:
        envGuards:
          type: array
          items:
            type: string
        keyCredentialsCertificatePolicyId:
          type: string
      required:
        - envGuards
        - keyCredentialsCertificatePolicyId
  responses:
    AgentResposne:
      description: Agent response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Agent"
    AgentConfigResponse:
      description: Agent config response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AgentConfig"
