openapi: 3.0.3
info:
  title: Cryptocat Agent Models
  version: 0.1.3
paths: {}
components:
  schemas:
    Agent:
      allOf:
        - $ref: "models-shared.yaml#/components/schemas/ApplicationByAppId"
        - $ref: "#/components/schemas/AgentFields"
        - x-go-type: agentComposed
    CreateAgentRequest:
      type: object
      properties:
        appId:
          description: The Application ID (Client ID) of the agent
          type: string
          x-go-type-skip-optional-pointer: true
        displayName:
          description: The display name of the agent application
          type: string
          x-go-type-skip-optional-pointer: true
    AgentFields:
      type: object
      properties: {}
  responses:
    AgentResposne:
      description: Agent response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Agent"
