openapi: 3.0.3
info:
  title: Cryptocat Cert Models
  version: 0.1.3
paths: {}
components:
  schemas:
    CertificatePolicy:
      allOf:
        - $ref: "models-shared.yaml#/components/schemas/Ref"
        - $ref: "#/components/schemas/CertificatePolicyFields"
        - x-go-type: certificatePolicyComposed
      required:
        - expiryTime
    CertificatePrivateKeyMode:
      type: string
      enum:
        - cloud-non-exportable
        - cloud-exportable
        - client
      x-enum-varnames:
        - CertificateKeyModeCloudNonExportable
        - CertificateKeyModeCloudExportable
        - CertificateKeyModeClient
      x-go-type-skip-optional-pointer: true
    CertificatePolicyFields:
      type: object
      properties:
        keySpec:
          $ref: "models-key.yaml#/components/schemas/JsonWebKeySpec"
        keyMode:
          $ref: "#/components/schemas/CertificatePrivateKeyMode"
        expiryTime:
          type: string
        issuerPolicyIdentifier:
          type: string
          x-go-type-skip-optional-pointer: true
        subject:
          $ref: "#/components/schemas/CertificateSubject"
        subjectAlternativeNames:
          $ref: "#/components/schemas/SubjectAlternativeNames"
        flags:
          type: array
          items:
            $ref: "#/components/schemas/CertificateFlag"
          x-go-type-skip-optional-pointer: true
      required:
        - keySpec
        - keyMode
        - expiryTime
        - issuerPolicyIdentifier
        - subject
    CreateCertificatePolicyRequest:
      type: object
      properties:
        displayName:
          type: string
          x-go-type-skip-optional-pointer: true
        issuerPolicyIdentifier:
          type: string
          x-go-type-skip-optional-pointer: true
        keySpec:
          $ref: "models-key.yaml#/components/schemas/JsonWebKeySpec"
        keyMode:
          $ref: "#/components/schemas/CertificatePrivateKeyMode"
        expiryTime:
          type: string
          x-go-type-skip-optional-pointer: true
        subject:
          $ref: "#/components/schemas/CertificateSubject"
        subjectAlternativeNames:
          $ref: "#/components/schemas/SubjectAlternativeNames"
        flags:
          type: array
          items:
            $ref: "#/components/schemas/CertificateFlag"
          x-go-type-skip-optional-pointer: true
      required:
        - subject
    CertificateSubject:
      type: object
      properties:
        cn:
          type: string
          x-go-name: CommonName
      required:
        - cn
    CertificateFlag:
      type: string
      enum:
        - serverAuth
        - clientAuth
      x-enum-varnames:
        - CertificateFlagServerAuth
        - CertificateFlagClientAuth
    SubjectAlternativeNames:
      type: object
      properties:
        dnsNames:
          type: array
          items:
            type: string
          x-go-type-skip-optional-pointer: true
          x-go-name: DNSNames
        ipAddresses:
          type: array
          items:
            type: string
            x-go-type: net.IP
          x-go-type-skip-optional-pointer: true
          x-go-name: IPAddresses
        emails:
          type: array
          items:
            type: string
          x-go-type-skip-optional-pointer: true
  responses:
    CertificatePolicyResponse:
      description: CertificatePolicy response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/CertificatePolicy"
