openapi: 3.0.3
info:
  title: Cryptocat Shared Models
  version: 0.1.3
paths: {}
components:
  schemas:
    Ref:
      type: object
      properties:
        id:
          type: string
          x-go-name: ID
        updated:
          type: string
          format: date-time
        updatedBy:
          type: string
        deleted:
          type: string
          format: date-time
        displayName:
          type: string
      required:
        - id
        - updated
        - updatedBy
    ProfileFields:
      type: object
      properties:
        applicationId:
          type: string
        servicePrincipalId:
          type: string
        servicePrincipalType:
          type: string
        userPrincipalName:
          type: string
        appId:
          type: string
        mail:
          type: string
    Profile:
      allOf:
        - $ref: "#/components/schemas/Ref"
        - $ref: "#/components/schemas/ProfileFields"
        - x-go-type: profileComposed
    NamespaceProvider:
      type: string
      enum:
        - profile
        - root-ca
        - int-ca
        - agent
        - service-principal
        - group
        - user
      x-enum-varnames:
        - NamespaceProviderProfile
        - NamespaceProviderRootCA
        - NamespaceProviderIntermediateCA
        - NamespaceProviderAgent
        - NamespaceProviderServicePrincipal
        - NamespaceProviderGroup
        - NamespaceProviderUser
    NumericDate:
      type: integer
      x-go-type: jwt.NumericDate
      x-go-type-import:
        name: jwt
        path: github.com/golang-jwt/jwt/v5
  responses:
    RefsResponse:
      description: Refs response
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/Ref"
    ProfileResponse:
      description: Profile response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Profile"
