name: Backend Build and Publish
on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/freeradius.yml"
      - "radius/Dockerfile"
      - "radius/docker-entrypoint.sh"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GiHub Action"
        uses: actions/checkout@v4

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: "Build and publish image"
        run: |
          az acr login --name ${{ vars.ACR_NAME }}
          docker build . -t ${{ vars.ACR_LOGIN_SERVER }}/freeradius/custom:${{ github.sha }} -t ${{ vars.ACR_LOGIN_SERVER }}/freeradius/custom:latest
          docker push ${{ vars.ACR_LOGIN_SERVER }}/freeradius/custom:${{ github.sha }}
          docker push ${{ vars.ACR_LOGIN_SERVER }}/freeradius/custom:latest
        working-directory: backend
