name: Frontend Build and Publish
on:
  push:
    branches:
      - "frontend-release"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GiHub Action"
        uses: actions/checkout@v3

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: "Build and publish image"
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.REGISTRY_REPO_NAME_FE }}:${{ github.sha }} -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.REGISTRY_REPO_NAME_FE }}:latest
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.REGISTRY_REPO_NAME_FE }}:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.REGISTRY_REPO_NAME_FE }}:latest
        working-directory: frontend

      - name: "Deploy to Azure Container Apps"
        run: |
          az containerapp update --name  ${{ secrets.CONTAINER_APP_NAME_FE }} --resource-group  ${{ secrets.RESOURCE_GROUP_NAME }} --image ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.REGISTRY_REPO_NAME_FE }}:${{ github.sha }}        
